### ISSUE TITLE
setTimeout throws "uncaught exception" in Chrome console

### ISSUE THREAD

**Issue by thbar** [recurly/recurly-js#171]
I'm using `recurly.Pricing()` API calls to evaluate a price, and despite setting a `.catch` block (which is properly executed), a `setTimeout` call throws the exception which is reported by Chrome as "Uncaught".

Exception raised:

`Uncaught missing-plan: A plan must be specified.`

Code raising the exception (in recurly.js, custom build with `make`):

```javascript
// In browsers, uncaught exceptions are not fatal.
// Re-throw them asynchronously to avoid slow-downs.
setTimeout(function () {
    throw e;
}, 0);
```

I don't know if this has any bad impact or not. I cannot share a fully runnable reproduction, but here is the triggering snippet (using coffeescript and knockout.js):

```coffeescript
# passing a wrong plan on purpose to trigger the error
recurly.Pricing()
  .plan("wrong-plan", { quantity: 1 })
  .currency('EUR')
  .address({
    # do we need more here?
    vat_number: @delayed_vat_number()
    country: @country()
  })
  .catch (err) =>
    # this is called properly
    @computing(false)
    @subtotal_now('')
    @vat_now('')
    @vat_rate('')
    @total_now('')
    @error_message("Price update failed. Please reload this page.")
  .done (price) =>
    @computing(false)
    @subtotal_now(price.currency.symbol + ' ' + price.now.subtotal)
    @vat_now(price.currency.symbol + ' ' + price.now.tax)
    @total_now(price.currency.symbol + ' ' + price.now.total)

    # grab back the vat rate(s)
    # in theory we could have multiple rates here - not in practice though afaik at this point
    taxes = _.map(price.taxes, (tax) => (tax.rate*100).toString() + '%')
    if taxes.length > 0
      @vat_rate('at ' + taxes.join(', '))
    else
      @vat_rate('')
```

Is this expected?

**Comment by chrissrogers** [comment]
I would expect this behavior. A `setTimeout` will run the passed function in a global context. Thus it will have escaped the context of the pricing chain, which would otherwise catch the exception being thrown. The only way to catch an error thrown in that setTimeout function would be to use a try-catch immediately around the code that might throw.

Are you intending to re-throw the missing-plan exception asynchronously?

**Comment by thbar** [comment]
I didn't want to re-throw the exception, I was just concerned that this error message might have consequences. But reading your comment I realize that it's hasn't got any, so I'll close this one.

Thanks!
