### ISSUE TITLE
Single use coupon not applied after recalculation

### ISSUE THREAD

**Issue by vince-happymetrix** [recurly/recurly-js#173]
In a script with to paying options (being monthly & yearly), i want to apply a coupon on the yearly subscription.
On init the coupons gets applied correctly. When i switch to monthly, the discount goes back to 0, which is correct. But when i select yearly again, the coupon is not applied anymore and discount still says 0.
Subtotal, tax and total are correct in all situations.

**Comment by vince-happymetrix** [comment]
I use recurly js v3.

**Comment by rachelquick** [comment]
Can you please contact support@recurly.com with your code and (ideally) a place where we can try to reproduce this behavior? Thanks.
