### ISSUE TITLE
Coupon code callback

### ISSUE THREAD

**Issue by merauluka** [recurly/recurly-js#176]
We are updating our code from v1 to v3 of the Recurly.js API. We have everything working so far except the coupon code field.

**Is there a way to return some meaningful value if the code is invalid?** At the moment we have the pricing information calculating, but the coupon code appears to only return data when the code is valid. *If the code is invalid it would be great to have some kind of message we could pass on to the user.*

We would like to mimic the functionality that used to appear in Recurly.js's buildSubscriptionForm form building call.

**Comment by chrissrogers** [comment]
> Is there a way to return some meaningful value if the code is invalid?

If you are calling the pricing API directly, the coupon method will throw an error with code 'not-found' for coupons which do not apply to the selected plan.

If you are attaching pricing to a form, then bad coupon codes are simply ignored [1]. I could see it being useful for an event to fire on the pricing instance if this occurs, though.

[1]: https://github.com/recurly/recurly-js/blob/master/lib/recurly/pricing/attach.js#L126-L129

**Comment by merauluka** [comment]
I am attaching pricing to my form. I ended up calling the pricing API directly when the coupon field is updated because I wanted to tell my users the status of their coupon code. But it would be cool to be able to do it all at once instead.

**Comment by chrissrogers** [comment]
Agreed. I think that instead of silencing not-found coupon errors, we can instead emit an event. `invalid.coupon` or something similar.

**Comment by thbar** [comment]
There is more things lacking with coupon JS API, actually. See [here](#225) for instance.

I would have assumed that the `done(price)` callback would have add things like coupon validity (yes/no),  period of applicability, a label.

I think the JS library is a bit lagging with functionalities around this area! (sure, I could issue an extra API call myself, but why do that when the Recurly.js library already does it but does not expose the information?).

Thanks for considering this!
