### ISSUE TITLE
Pricing.attach: check that event target is a valid data-recurly element

### ISSUE THREAD

**Issue by chrissrogers** [recurly/recurly-js#181]
##### Summary
- `pricing.attach` will call [change](https://github.com/recurly/recurly-js/blob/master/lib/recurly/pricing/attach.js#L44) on initialization. `change` will then look for an event on the stack in order to determine a target. This helps it focus its pricing change scope to a single element change.
- if `pricing.attach` is called during an event, say `document.ready`, it will confuse this initialization into thinking it is acting upon the `window.document` because of this [IE fallback](https://github.com/recurly/recurly-js/blob/master/lib/recurly/pricing/attach.js#L48).
##### Solution
- pricing's [target function](https://github.com/recurly/recurly-js/blob/master/lib/recurly/pricing/attach.js#L90) needs to check that the target element is a `data-recurly` element
##### Example

http://jsfiddle.net/he8pk8cL/2/

**Comment by chrissrogers** [comment]
@jlujan-bgrove (pretty sure this is the acct of the reporter)

**Comment by jlujan-bgrove** [comment]
I am the reporter. Thanks for the update.

**Comment by chrissrogers** [comment]
A quick and dirty workaround if a merchant needs to run `pricing.attach` calls in a `document.ready` event listener is to wrap the `pricing.attach` call in a `setTimeout`. This will decouple the pricing calls from the stack the `document.ready` event is on and free the pricing call to initialize all inputs.

That said, I will prioritize a fix or this as it is a very non-obvious bug for a common use-case of running pricing calls within a `ready` listener.

```js
$(function () {
  // we're in a document.ready listener. Therefore window.event might be set
  // ...
  // Use setTimeout to run the pricing attach on another stack frame from the ready event
  setTimeout(function () {
    var pricing = recurly.Pricing();
    pricing.attach(document.querySelector('form'));
    // ...
  }, 0);
});
```

**Comment by chrissrogers** [comment]
The pricing.on('attached') event is an ideal method to counteract this behavior.
