### ISSUE TITLE
Add built version of script to tagged revisions

### ISSUE THREAD

**Issue by icio** [recurly/recurly-js#182]
Most libraries available through bower are packaged with a built version of the script so that the development flow of users looks something like:

```
bower install recurlyjs
cp bower_components/recurlyjs/build/recurly.min.js public/js/
```

It's quite common for libraries of this nature to keep built/minified scripts in a dist/build directory, with the understanding that they're only updated with each new release, and ask that contributors don't submit patches to the minified files.

**Comment by chrissrogers** [comment]
Excellent suggestion. This will be added to the next release.

**Comment by icio** [comment]
:smile: Glad to hear it. I do have a minor concern about the idea, however, that I wanted to raise.

I'm wondering whether using recurly-js from a fixed bower version might introduce a discrepancy between what the client website is running and what is compatible with the recurly API servers. For example, in the README it states that "A later version of Recurly.js will switch over to using CORS+XHR exclusively" but if a user has fixed at a version of Recurly.js which continues to use JSONP and then API server drops support for JSONP, their customer's payments will fail.

Obviously I don't know what your intentions are with the API. Maybe this won't be a problem, but I thought I'd raise. :+1:

**Comment by chrissrogers** [comment]
@icio Yes, that is certainly a valid concern. We encourage everyone to load recurly.js from our CDN to ensure the latest version is always used. Since the Recurly.js server-side API is not intended for public usage, but only for Recurly.js, we wouldn't take steps to inform of API breakages.

**Comment by chrissrogers** [comment]
in #190 I have changed the build target to ./build to conform more with bower and other dependency tools' conventions. I haven't gone so far as to unignore the build targets, though, since I think it would be good to discuss how easily we should make it for people to download locked versions of the library. Our mission is to have as many sites using the version hosted on our CDN as possible.

**Comment by chrissrogers** [comment]
I'm going to close this for now, as we would prefer everyone load the script via CDN. This ensures the newest version is always loaded, and that code which handles sensitive customer information is always hosted and secured by Recurly.

Thus we'd rather require those that wish to pull Recurly.js as a dependency through bower/component/duo go through the extra step of building the project, than encourage people not to load Recurly.js from our CDN.

**Comment by icio** [comment]
In which case I might recommend you remove the project from bower to avoid future confusion.

**Comment by chrissrogers** [comment]
Mm yes, probably for the best. Thanks for keeping a close eye on this.
