### ISSUE TITLE
Coupon handling suggestion

### ISSUE THREAD

**Issue by davidmcl** [recurly/recurly-js#203]
It would be helpful to include the duration (I think it's called Lifespan on the admin console) of the coupon when the Coupon object is returned similar to what is done in the api call in case you have a coupon whose terms is like $5 off for 6 months. That would allow the full information to be displayed to the customer without additional api calls.

Currently that information is ommitted.
```
Coupon {"code":"test0430a","name":"Test 04-30-2015a","discount":{"type":"dollars","amount":{"USD":5}},"single_use":false}
```

Additionally, like others have mentioned previously, The silent fail of an invalid coupon requires me to separately apply coupons and test for ```undefined``` being returned.

As a suggestion, would it not be possible to return the coupon info in the 'done' Price object similar to what you are doing with the currency and addons? 

Then if the Coupon object in that structure was ```undefined``` it would signal that an error occurred, or if a valid it would be easy to access it there with the other info currently used.

Thanks,
David

**Comment by snodgrass23** [comment]
The `Lifespan` property is actually just a different wording on the `single_use` property.  There is also a 'redeem_by' date property that isn't being included in the return right now.

![screen shot 2015-05-08 at 10 25 31 am](https://cloud.githubusercontent.com/assets/405400/7538327/0c06bc60-f56d-11e4-989b-6bd7ef54129f.png)

**Comment by davidmcl** [comment]
re: _The Lifespan property is actually just a different wording on the single_use property_

Actually that is not true...if you look at one of the coupon's detail returned from the api call to ...https://:subdomain.recurly.com/v2/coupons... you'll notice that the `Lifespan` is based on the `applies_for_months` property (empty === 'Forever')  -- the `single_use` propertty is a separate boolean.

```
<coupon href="https://subdomain.recurly.com/v2/coupons/test0426a">
    <redemptions href="https://subdomain.recurly.com/v2/coupons/test0426a/redemptions"/>
    <coupon_code>test0426a</coupon_code>
    <name>Test 04-26-2015a</name>
    <state>redeemable</state>
    <description>Payment page description</description>
    <discount_type>percent</discount_type>
    <discount_percent type="integer">25</discount_percent>
    <invoice_description>test0426 invoice description</invoice_description>
    <redeem_by_date type="datetime">2016-01-01T04:59:59Z</redeem_by_date>
    <single_use type="boolean">false</single_use>
    <applies_for_months type="integer">6</applies_for_months>
    <max_redemptions type="integer">100</max_redemptions>
    <applies_to_all_plans type="boolean">false</applies_to_all_plans>
    <created_at type="datetime">2015-04-26T16:57:55Z</created_at>
    <plan_codes type="array">
      <plan_code>plus_monthly</plan_code>
      <plan_code>plus_annual</plan_code>
    </plan_codes>
    <a name="redeem" href="https://subdomain.recurly.com/v2/coupons/test0426a/redeem" method="post"/>
  </coupon>
```

...and while I agree that `redeem_by_date` would be good for completeness on a valid coupon, it's a bit immaterial here, as if the `redeem_by_date` has already passed the coupon validation will error out and the Coupon will be `undefined` anyway.

dbm

**Comment by snodgrass23** [comment]
Yeap, I just looked again and the `applies_for_months` property is taken into account along with the `single_use` property when determining the coupon's `lifespan`. We basically combine them in the UI to make it easier to fill out the form in the admin console.

I can make an update to the api to also send back the `applies_for_months` property.

**Comment by davidmcl** [comment]
Thanks - that will help.

David

**Comment by snodgrass23** [comment]
I've put in a patch to add this. It's just waiting on review and approval.

**Comment by snodgrass23** [comment]
The patch has been deployed.

**Comment by davidmcl** [comment]
great, thanks for quick response.
