### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by grabcode** [recurly/recurly-js#216]
Am I wrong saying there's no more bower support with v > 3.0.11 ?
What would the reason(s) for that ?

Thanks

**Comment by billychan** [comment]
Same question here. Saw bower was removed recently in favor of Component. We have project which workflow depending on bower and feel it inconvenient. 

Is it possible to add it back?

Thanks!

**Comment by iamdarrenhall** [comment]
Yeah, I'd also appreciate having bower support added back in.

**Comment by grabcode** [comment]
@chrissrogers would you have any update please?

**Comment by chrissrogers** [comment]
Hey guys. More info on removing bower support can be found in #182 -- it basically came down to not wanting to commit the build, and that pattern not being ideal for bower. I'm open to adding it back in if there is an amenable bower distribution pattern that doesn't involve committing the build.

**Comment by billychan** [comment]
Thanks @chrissrogers. Totally understand the concern of matching backend changes.

Could you please confirm if master branch is the same as https://js.recurly.com/v3/recurly.js ? If so I think we might be good to use the master branch in bower.json without bothering changing Recurly repo, with the benefit of getting updated lib.

Guys how do you think about that?

**Comment by chrissrogers** [comment]
The master branch wouldn't be guaranteed to be the same as the version we host.. and it may even be that master breaks. This is unlikely, but there are fewer machine controls around merging into master than there are deploying a version of Recurly.js to our hosted environment.

Could you reference a specific tag, say, the latest released version (currently [v3.1.1](https://github.com/recurly/recurly-js/tree/v3.1.1))?

**Comment by billychan** [comment]
Yes the concern is still backend if using a specific brach at our side, I'm afraid we are not able to watch the changes in time.

For now it looks our best choice is still hosted version seeing master is not totally reliable as you suggested.  Maybe someday in the future there would be a trustworthy branch say release and we can use it in bower then, that would be convenient. 

Thank you again @chrissrogers
