### ISSUE TITLE
Update account details with v3

### ISSUE THREAD

**Issue by grabcode** [recurly/recurly-js#217]
Hi,

How would I update the name or address of an account without having any credit card details ?

I manage to create a new subscription using recurly.js v3, retrieving a token after sending across a payload container billing info (user details+payment details). But I can't consume the same recurly.token in order to update exclusively the user details as the validation requires me the full payment details.

Kindly,
Alex

**Comment by chrissrogers** [comment]
This is not possible with Recurly.js, as such an operation would require using our backend API using your private key. Please see documentation [here](https://dev.recurly.com/).

**Comment by chrissrogers** [comment]
But to clarify further: You may simply call the API with the updated fields, without packing them into a token. Those values may be sent plainly.
