### ISSUE TITLE
Billing info form defaults to 'United States' regardless of country specified.

### ISSUE THREAD

**Issue by markdorison** [recurly/recurly-js#218]
When a billing info form is created, it renders 'United States' as the default selection regardless of the country specified. This is visible even in the [billing info example where 'GB' is specified](https://github.com/recurly/recurly-js/blob/v2/examples/update_billing_info.html#L14-L15).

![screen shot 2015-07-26 at 17 03 52](https://cloud.githubusercontent.com/assets/20355/8912352/4f782038-3460-11e5-99f5-d5dbaf8611d0.png)

Note: I am seeing this in the v2 branch. I am unsure if it is also present in v3.

**Comment by chrissrogers** [comment]
Hi @markdorison -- we unfortunately do not support Recurly.js v2 any more aside from high-risk security fixes. I recommend upgrading to v3, which will allow you to create a much nicer form with more control over design and functionality.

Take a look at https://docs.recurly.com/js for more on the new version :)

**Comment by markdorison** [comment]
In case others find this when searching, the country field is set via geo-location by default which is why it is not respecting the specified country value. To disable this, you can pass in ```enableGeoIP: false``` as shown below:

```javascript
Recurly.config({
    subdomain: 'recurlyjsdemo-test',
    currency: 'GBP',
    country: 'GB',
    VATPercent: 10,
    enableGeoIP: false
  });
```
