### ISSUE TITLE
VAT numbers and tax exclusion

### ISSUE THREAD

**Issue by spebbe** [recurly/recurly-js#222]
Currently, adding a VAT number using pricing.tax({vat_number: someVATNumber, tax_code: 'digital'}) doesn't seem to trigger tax exclusion or really influence the tax calculation at all. Is this the intended behaviour and if so, is there another way to specify tax exclusion? Thanks!

**Comment by chrissrogers** [comment]
Hi @spebbe -- this most likely depends on your site's tax configuration. [These docs](https://docs.recurly.com/docs/tax) will shed some light on some of the complexities -- and if there are still issues, please pop back in here with a way to reproduce and I'll check into it.
