### ISSUE TITLE
allow `catch` a pricePromise after `done`

### ISSUE THREAD

**Issue by gagalago** [recurly/recurly-js#223]
I have try to use the pricePromise sytem inside angular

```js
planPrice = function(planCode) {
  var deferred;
  deferred = $q.defer();
  recurly.Pricing().plan(planCode, {
    quantity: 1
  }).currency("EUR").done(function(price) {
    console.log(price);
    deferred.resolve(parseFloat(price.base.plan.unit));
  }).catch(function(err) {
    console.log(err);
    return deferred.reject(err);
  });
  return deferred.promise; //never returned
};
```

But in this order `planPrice` never return the angular promise. I have to change the order of `catch` and `done` to have the normal behaviour : an angular promise base on a pricePromise.

```js
planPrice = function(planCode) {
  var deferred;
  deferred = $q.defer();
  recurly.Pricing().plan(planCode, {
    quantity: 1
  }).currency("EUR").catch(function(err) {
    console.log(err);
    return deferred.reject(err);
  }).done(function(price) {
    console.log(price);
    deferred.resolve(parseFloat(price.base.plan.unit));
  });
  return deferred.promise; // angular promise returned
};
```

So is it possible to have no order of these two functions (`catch` and `done`) ?

**Comment by chrissrogers** [comment]
Your example demonstrates this, but yes,`catch` will only handle errors distinctly from `done` if it is chained before `done`, since `done` will not return a promise. This is a limitation inherent to the basis of Recurly's `Promise`: [then/promise](http://github.com/then/promise).
