### ISSUE TITLE
Example of how to implement backend-less recurly usage with CORS

### ISSUE THREAD

**Issue by HadrienPierart** [recurly/recurly-js#224]
Hi there,

I can read at the end of the documentation that it is possible to call recurly API directly in javascript, from a frontend application, thanks to the publicKey and the cors option set to true. But that's it. No example of this anywhere :(

I have tried various implementations but most of the time, here is what I get back from the API (for /plans or /subscriptions for instance) : 

    No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9090' is therefore not allowed access. The response had HTTP status code 401.

Which is a classical error when cors is not activated on the endpoint API.

Is there some documentation somewhere that I could use ?

Thanks !

**Comment by chrissrogers** [comment]
Hi @HadrienPierart -- it seems as though you may have confused our APIs. Recurly.js uses a public API specific to Recurly.js, which is entirely distinct from our main backend API (which contain the /plans and /subscriptions endpoints).

We do not support calling our main API from a browser, and **highly** suggest you not do this. Doing so would require exposing your privte API key, allowing an attacker to manipulate your data within Recurly at will.

CORS is simply a data transmission option for Recurly.js and does not pertain to our main API.
