### ISSUE TITLE
get coupon description - hosted_description

### ISSUE THREAD

**Issue by henryoswald** [recurly/recurly-js#225]
It would be great if when applying a coupon we can get the description, it looks to be hosted_description in the xml response.

**Comment by thbar** [comment]
I asked this to the support (how to get both the description but also the period of application, e.g. number of months) and the reply last week was to issue a coupon request myself (on the [server side](https://dev.recurly.com/docs/list-active-coupons)).

That said the Recurly.js library is already itself issuing a call to check the coupon, so all this information is available somewhere, so why not propagating it to the `done` callback?

To me the `done(price)` callback should provide the data, including coupon application success or not (valid_coupon?), period of application, description etc.

**Comment by thbar** [comment]
After a number of hours of digging, I actually found a way to get more information, but I think the order of the calls are important and maybe why I missed this initially.

If I use this, then I'll get the detailed coupon information:

```coffeescript
recurly.Pricing()
  .plan(@recurly_plan(), { quantity: 1 })
  .currency(@currency())
  .on 'set.coupon', (coupon) =>
    @setCouponDescription(coupon)
  .on 'unset.coupon', () =>
    @clearCouponDescription()
  .coupon @coupon_code()
  .address(address)
  .catch (err) =>
    # snip
  .done (price) =>
    # snip
```

With this exact order, I will get detailed information on `set.coupon`.

**Comment by chrissrogers** [comment]
Thank you for answering this @thbar -- yes, the pricing promise chain will only resolve with price data -- we chose not to make this polymorphic to make it easier to trust its output.

The [`set.coupon`](https://docs.recurly.com/js/#events17) event is the correct event to listen to on the pricing object in order to read coupon data.
