### ISSUE TITLE
Credit card validation bug

### ISSUE THREAD

**Issue by abhilashmurthy** [recurly/recurly-js#226]
`recurly.validate.cardNumber(41111)` returns true
It's not supposed to

**Comment by chrissrogers** [comment]
Thanks @abhilashmurthy

`validate.cardNumber` implements the Luhn algorithm without a practical length check. I'll add one. Just a heads up that the shortest card number we're aware of is 12 digits -- this will be the minimum.

**Comment by chrissrogers** [comment]
This has been fixed in [#134349](https://github.com/recurly/recurly-js/commit/134349011f3eec8e1468d5c9e4c6af611cf690bd)
