### ISSUE TITLE
Paypal popup blocked in IE

### ISSUE THREAD

**Issue by gebrkn** [recurly/recurly-js#232]
When using `recurly.paypal`, the popup is blocked in MSIE (IE 11 on Win10, default settings).

Code to reproduce:

```
<script src="https://js.recurly.com/v4/recurly.js"></script>
<script>
    onload = function () {
        recurly.configure('xxx');
        document.getElementById('paypal-button').addEventListener('click', function () {
            recurly.paypal({
                description: 'test'
            }, function (err, token) {
                alert(JSON.stringify([err, token]))
            });
        });
    }
</script>
<button id="paypal-button">paypal</button>
```

Expected result (as in Chrome, FF, Edge): a new tab opens for a second and closes itself, the main page displays an error message.

Actual result in IE: the standard warning "Internet Explorer blocked a popup..." is displayed on the bottom of the page.

**Comment by chrissrogers** [comment]
Thanks for reporting this @gebrkn -- I'll have a look at this soon

**Comment by chrissrogers** [comment]
The typical behavior of this is that a click event can instigate a new window event, as long as they are on the same active call stack -- i.e. no async interruption. This doesn't appear to be the case in your code sample, and I personally haven't been able to get IE11 to block the PayPal window from opening. If this is still occurring, any additional information that could help reproduce the error would help us get to the bottom of the issue you're having.

**Comment by davedevelopment** [comment]
I also get the popup blocked by IE11.

![About IE](https://s3.amazonaws.com/atst-solutions/screenshots/20170313101822.png)
![Windows 7](https://s3.amazonaws.com/atst-solutions/screenshots/20170313101932.png)

``` html
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
    <script src="https://js.recurly.com/v4/recurly.js"></script>
</head>
<body>

<form method="post" class="paypal-form" action="/payment/71#paypal">
    <input type="hidden" data-recurly="token" name="recurly-token" id="recurly-token" />
    <button type="submit" class="" title="Pay with Paypal">
        Pay by Paypal
    </button>
</form>


<script>
(function () {

    var $ = window.jQuery;

    recurly.configure({
        publicKey: 'XXXXXXXXXXXXXXXXXXXXXXXXXx'
    });

    $('.paypal-form').on('submit', function (event) {
        event.preventDefault();

        var form = this;
        recurly.paypal({ description: 'Month' }, function (err, token) {
            if (err) {
                console.log(err);
                return;
            }

            $('#recurly-token').val(token.id);
            form.submit();
        });
    });
})();
</script>
</body>
</html>

```
