### ISSUE TITLE
iframe form divs empty

### ISSUE THREAD

**Issue by jerols** [recurly/recurly-js#235]
I have been chatting with @bhelx on IRC and he said to post this here.

I am trying to implement a basic payment form via recurly.js. I followed the instructions here: https://docs.recurly.com/js/?php#how-it-works

I used recurly.configure([my public key]) and that object seems to generate but I noticed I can put anything in the key and there are no JS errors so not sure how to debug if the basic setup is happening or not. I also copied and pasted the basic HTML form directly into my HTML. What I end up with is the first name and last name forms and a bunch of empty data-recurly divs.

I set window.localStorage.debug = 'recurly:*' to help with debugging. This resulted in two debug messages, see below:

I believe the key is found in the 3 errors I attached as a screenshot. I also attached another screenshot with more info.
<img width="650" alt="screen shot 2016-02-11 at 2 08 34 pm" src="https://cloud.githubusercontent.com/assets/116126/12987332/9d02936e-d0c9-11e5-9547-e2aaee2753f1.png">
<img width="1201" alt="screen shot 2016-02-11 at 2 11 54 pm" src="https://cloud.githubusercontent.com/assets/116126/12987333/9d062b14-d0c9-11e5-857e-9154f3777b9c.png">

I should mention that I am attempting to implement this in a single page Angular application. recurly.configure([my public key]) is called in the app.js (where most initialization occurs) but the form is on a preferences screen, which has a HTML template (containing the recurly form) and a controller (which currently doesn't do anything with recurly.)

**Comment by chrissrogers** [comment]
Hi! When you call `recurly.configure`, recurly.js will look for an html target within which to inject the iframe fields for number, exp month, and exp year. Are you certain that those targets are present in the html of the page at the time you are making the `recurly.configure` call. This is highlighted in the [form](https://docs.recurly.com/js/#build-a-card-form) section of the documentation.

Per your question about the public key: that value is only used when API requests occur (for instance, when you call `recurly.token`) -- an invalid public key would generate an error at that time.

**Comment by jerols** [comment]
@chrissrogers thanks for the help. That was it — The HTML must have not been rendered by the time recurly.configure was called. Because of the way Angular works, I think the only way for this to work is if I place the javascript in my HTML template instead of in the Angular controller and that did indeed work for me.
Looking back at the documentation, I would recommend making it clearer that the HTML needs to be present at the time you call recurly.configure for it to work.

**Comment by bhelx** [comment]
@jerols I don't remember a lot about angular, but is there some kind of hook that you can tie into after the dom from your template is loaded? Something equivalent to `componentDidMount()` in React would maybe work.

**Comment by chrissrogers** [comment]
Thank you for that suggestion @jerols -- I have updated the docs accordingly.

**Comment by chrissrogers** [comment]
Going to close this as resolved. Please reopen if anything else on this subject arises. Thanks again for the questions and suggestions @jerols
