### ISSUE TITLE
Styling for Recurly fields

### ISSUE THREAD

**Issue by martinpesout** [recurly/recurly-js#241]
I've found the problem with styling for Recurly fields. I need to set font smoothing. Something like this in CSS:

```
-webkit-font-smoothing: antialiased;
-moz-osx-font-smoothing: grayscale;
```

I tried to use API for styling and this property seems to be unsupported: 

```
        recurly.configure({
            publicKey: XXX,
            style: {
                all: {
                    fontColor: '#263340',
                    fontFamily: 'Roboto, sans-serif',
                    fontSize: '16px',
                    fontWeight: '300',
                    fontSmoothing: 'antialiased',
                    webkitFontSmoothing: 'antialiased';
                },
            },
        });
```

Is there any way how to achieve antialiased font smoothing? Thank you

**Comment by chrissrogers** [comment]
Hi @martinpesout -- We don't currently support passing in the `fontSmoothing` property, but I don't see why we can't :) I'm going to make this a feature request.

**Comment by martinpesout** [comment]
Cool. Thanks a lot.

**Comment by chrissrogers** [comment]
I'm currently on the fence about this, since it's not a standard property. Is the goal to achieve smooth fonts, or to reduce smoothing? It looks lik the browser defaults are to use sub-pixel smoothing.

**Comment by chrissrogers** [comment]
Closing this for now due to the non-standard nature of the property.

**Comment by martinpesout** [comment]
I understand that that it's not standard property, on the other hand the difference is significant. I'm using font called Roboto which is standard font in Google Webfons.

Tested in Chrome:

![snimek obrazovky 2016-07-27 v 22 35 07](https://cloud.githubusercontent.com/assets/239468/17191493/6a6c4cf6-544a-11e6-8078-b3f535434308.png)

![snimek obrazovky 2016-07-27 v 22 38 47](https://cloud.githubusercontent.com/assets/239468/17191610/efe9426c-544a-11e6-86d3-627889783fa6.png)

First two field are non-recurly and you can see font is thinner. I have no way how to make recurly field the same as other fields.

**Comment by chrissrogers** [comment]
Is the only stylistic difference the font smoothing? Would you mind sharing the style properties of your normal fields as rendered by Chrome vs those in the fields?

**Comment by martinpesout** [comment]
Yes exactly. There is no another property how I can achieve it. See Recurly field using Roboto font with font smoothing off and on:

![snimek obrazovky 2016-07-27 v 22 47 00](https://cloud.githubusercontent.com/assets/239468/17191858/498b4ef4-544c-11e6-9a93-bcc80e3fb300.png)

![snimek obrazovky 2016-07-27 v 22 47 10](https://cloud.githubusercontent.com/assets/239468/17191861/4ed807f8-544c-11e6-937b-0f76ca039256.png)

**Comment by martinpesout** [comment]
My styling for Recurly field: 

![snimek obrazovky 2016-07-27 v 22 51 41](https://cloud.githubusercontent.com/assets/239468/17192005/feb28126-544c-11e6-9b49-2d52502e53da.png)

My styling for non-recurly field:

![snimek obrazovky 2016-07-27 v 22 52 43](https://cloud.githubusercontent.com/assets/239468/17192026/0f12e2c2-544d-11e6-8030-2e9d17c8e614.png)

I have 

```
html, body {
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
```

This is not something weird property. For example if you check well-known frontend framework Zurb Foundation http://foundation.zurb.com/ they are also using it. It's non-standard but for some fonts it's important in webkit browsers.

**Comment by chrissrogers** [comment]
Thanks for the demonstration, it's very very helpful. My hesitation was largely in that it seemed it could now be standardized amongst the two implementations, given their values do not intersect.

However, what do you think of this implementation? It reflects a behavior of disabling/enabling(default) osx font smoothing.

```js
recurly.configure({
  style: {
    all: {
      fontSmoothing: 'auto' // 'off', 'antialiased'
    },
  }
});
```

Would have the corresponding results

'auto'

no effect

'off'

```css
-webkit-font-smoothing: none;
-moz-osx-font-smoothing: grayscale;
```

'antialiased'
```css
-webkit-font-smoothing: antialiased;
-moz-osx-font-smoothing: unset;
```

The default would be 'on', which would

**Comment by martinpesout** [comment]
I like your idea:

There is the only one difference. I don't think that this property `-moz-osx-font-smoothing:unset;` exists. Let's try this for `off` option:

```
-moz-osx-font-smoothing: initial;
```

---

So summary will be:

**auto**

_no effect_

**off**

```
-webkit-font-smoothing: none;
-moz-osx-font-smoothing: initial;
```

**antialiased**

```
-webkit-font-smoothing: antialiased;
-moz-osx-font-smoothing: grayscale;
```

**Comment by chrissrogers** [comment]
I was going off the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth), but those could be out of date, so I'll test first-hand to see what actually works.

**Comment by martinpesout** [comment]
You are right. I chose recommendation for Google Chrome Console for `-moz-osx-font-smoothing`. In this case I think that better to trust https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth in this.

**Comment by chrissrogers** [comment]
I've added this support, and will drop a note here once it is available in production. The soonest would be one week from today.

**Comment by martinpesout** [comment]
Hi, is there any progress with implementation `font-smoothing`?

**Comment by chrissrogers** [comment]
Ah yes, it has been publicly released. Enjoy!

**Comment by martinpesout** [comment]
Hi I have one more question about styling. We were talking about `font-smoothing` and it works like a charm. But I've realized that we have one more specific usage. See next screenshot:

![snimek obrazovky 2016-09-22 v 15 15 50](https://cloud.githubusercontent.com/assets/239468/18749814/d1a5c306-80d8-11e6-9452-ffc14c0dd801.png)

First line contains normal form fields and second and third line contains Recurly fields. We are using custom styling for placeholders. I want to ask you about possibility to add support for this.

In our code we use next definitions:

```
input::-webkit-input-placeholder {
	font-style: italic;

	color: PLACEHOLDER_COLOR_CODE;
}

input::-moz-placeholder {
	font-style: italic;

	color: PLACEHOLDER_COLOR_CODE;
}
```

Is it possible to add something like this into `recurly-js`:

```
recurly.configure({
  style: {
    all: {
      placeholderFontColor: '#000', // color code
      placeholderFontStyle: italic, // normal|italic|oblique|initial|inherit
    },
  }
});
```

Thanks

**Comment by chrissrogers** [comment]
You're in luck, as this is currently supported. It's slightly hinted at [in the docs](https://dev.recurly.com/docs/getting-started-1#section-styling-card-fields) (see the placeholder section of the config object there). You can set any css property supported by those pseudo selectors there.

**Comment by martinpesout** [comment]
@chrissrogers Hi I see it. Is it possible to have one request. I see that it's possible to specify just color for placeholder

```
placeholder: {
    color: '#98A5B3',
}
```

Do you think that can be possible to extend it and allow to define font-style, font-weight and font-smootning?

```
placeholder: {
    color: '#98A5B3',
    fontStyle: 'italic',
    fontWeight: '300',
    fontSmoothing: 'antialiased',
}
```

Thanks a lot.

**Comment by chrissrogers** [comment]
@martinpesout Yep that is currently possible. Go ahead and drop those values in and they will be reflected in browsers that support those properties on placeholders.

**Comment by martinpesout** [comment]
@chrissrogers sorry for delay in my answer. I've found what kind of problem I have. Let me explain it to you. This is my config:

```
recurly.configure({
			publicKey: RECURLY_PUBLIC_KEY,
			style: {
				all: {
					fontColor: '#263340',
					fontFamily: 'Roboto',
					fontSize: '16px',
					fontSmoothing: 'antialiased',
					fontWeight: '300',
					placeholder: {
						color: '#98A5B3',
						fontStyle: 'italic',
						fontWeight: '300',
						fontSmoothing: 'antialiased',
					},
				},
				number: {
					placeholder: {
						content: intl.formatMessage(messages.cardNumber),
					},
				},
				month: {
					placeholder: {
						content: intl.formatMessage(messages.monthShortcut),
						fontSmoothing: 'antialiased'
					},
				},
				year: {
					placeholder: {
						content: intl.formatMessage(messages.yearShortcut),
					},
				},
			},
		});
```

Problem is in `fontFamily` definition. I need to support special character and italic font style in Google font. So I need to import this

`<link href="//fonts.googleapis.com/css?family=Roboto:300,300i&amp;subset=latin,latin-ext" rel="stylesheet" type="text/css">`

instead of simple `<link href="//fonts.googleapis.com/css?family=Roboto" rel="stylesheet" type="text/css">`.

I need to have support for Czech clients and we accept special character like `ščřžý` and italic style so I need to define `Roboto:300,300i&amp;subset=latin,latin-ext` as source of Google Font. Is there any chance to support this? 

If I'll place this into recurly config: 

`fontFamily: 'Roboto:300,300i&amp;subset=latin,latin-ext',`

recurly-js will add this into code:

![snimek obrazovky 2016-10-10 v 12 14 05](https://cloud.githubusercontent.com/assets/239468/19232990/1718080a-8ee3-11e6-898a-ca7ba140e94a.png)

So `recurly-js` will try to load this source `https://fonts.googleapis.com/css?family=Roboto:300%7C300i&amp;subset=latin%7Clatin-ext` instead of correct form `https://fonts.googleapis.com/css?family=Roboto:300,300i&amp;subset=latin,latin-ext`

**Comment by chrissrogers** [comment]
@martinpesout thanks for reporting that issue. I see it's to do with the configuration encode/decode. I've taken note to fix this

**Comment by martinpesout** [comment]
Hi @chrissrogers I need to ask you about status of encode/decode issue mentioned here https://github.com/recurly/recurly-js/issues/241#issuecomment-252580486? We have still problem with styling 

Thanks

**Comment by chrissrogers** [comment]
@martinpesout still looking into a fix at the moment. Encoding and decoding configuration values gets to be sensitive since we must ensure the inputs are safe.

A practical consideration I was wondering about though, is if you need the latin-ext in the fields. The italic style I understand, given the fields are italicized. But the input values are typically restricted to numbers.
