### ISSUE TITLE
Basic usage of library doesn't work.

### ISSUE THREAD

**Issue by frewsxcv** [recurly/recurly-js#248]
Source:

```html
<form>
  <input type="text" data-recurly="first_name">
  <input type="text" data-recurly="last_name">
  <div data-recurly="number"></div>
  <div data-recurly="month"></div>
  <div data-recurly="year"></div>
  <div data-recurly="cvv"></div>
  <input type="hidden" name="recurly-token" data-recurly="token">
  <button>submit</button>
</form>
<script src="https://js.recurly.com/v4/recurly.js"></script>
<script>
recurly.configure('sjc-bpUMSczM3JXCvbPodSbPac');
</script>
```

Screenshot:

![screen shot 2016-04-20 at 3 03 29 pm](https://cloud.githubusercontent.com/assets/416575/14686957/111ba75c-0709-11e6-854f-ef2695ba7c7e.png)

Generated HTML after render:

```html
<html>
  <head></head>
  <body>
    <form>
      <input type="text" data-recurly="first_name">
      <input type="text" data-recurly="last_name">
      <div data-recurly="number">
        <div class="recurly-hosted-field recurly-hosted-field-number">
          <iframe src="https://api.recurly.com/js/v1/field?config=%7B%22type%22%3A%22number%22%2C%22selector%22%3A%22%5Bdata-recurly%3Dnumber%5D%22%2C%22style%22%3A%7B%7D%2C%22recurly%22%3A%7B%22currency%22%3A%22USD%22%2C%22timeout%22%3A60000%2C%22publicKey%22%3A%22sjc-bpUMSczM3JXCvbPodSbPac%22%2C%22parent%22%3Atrue%2C%22cors%22%3Afalse%2C%22api%22%3A%22https%3A%2F%2Fapi.recurly.com%2Fjs%2Fv1%22%2C%22style%22%3A%7B%7D%2C%22fields%22%3A%7B%22number%22%3A%22%5Bdata-recurly%3Dnumber%5D%22%2C%22month%22%3A%22%5Bdata-recurly%3Dmonth%5D%22%2C%22year%22%3A%22%5Bdata-recurly%3Dyear%5D%22%2C%22cvv%22%3A%22%5Bdata-recurly%3Dcvv%5D%22%7D%2C%22required%22%3A%5B%5D%7D%7D" border="0" frameborder="0" allowtransparency="true" scrolling="no" style="height: 100%; width: 100%; background: transparent;">
          </iframe>
        </div>
      </div>
      <div data-recurly="month">
        <div class="recurly-hosted-field recurly-hosted-field-month">
          <iframe src="https://api.recurly.com/js/v1/field?config=%7B%22type%22%3A%22month%22%2C%22selector%22%3A%22%5Bdata-recurly%3Dmonth%5D%22%2C%22style%22%3A%7B%7D%2C%22recurly%22%3A%7B%22currency%22%3A%22USD%22%2C%22timeout%22%3A60000%2C%22publicKey%22%3A%22sjc-bpUMSczM3JXCvbPodSbPac%22%2C%22parent%22%3Atrue%2C%22cors%22%3Afalse%2C%22api%22%3A%22https%3A%2F%2Fapi.recurly.com%2Fjs%2Fv1%22%2C%22style%22%3A%7B%7D%2C%22fields%22%3A%7B%22number%22%3A%22%5Bdata-recurly%3Dnumber%5D%22%2C%22month%22%3A%22%5Bdata-recurly%3Dmonth%5D%22%2C%22year%22%3A%22%5Bdata-recurly%3Dyear%5D%22%2C%22cvv%22%3A%22%5Bdata-recurly%3Dcvv%5D%22%7D%2C%22required%22%3A%5B%5D%7D%7D" border="0" frameborder="0" allowtransparency="true" scrolling="no" style="height: 100%; width: 100%; background: transparent;">
          </iframe>
        </div>
      </div>
      <div data-recurly="year">
        <div class="recurly-hosted-field recurly-hosted-field-year">
          <iframe src="https://api.recurly.com/js/v1/field?config=%7B%22type%22%3A%22year%22%2C%22selector%22%3A%22%5Bdata-recurly%3Dyear%5D%22%2C%22style%22%3A%7B%7D%2C%22recurly%22%3A%7B%22currency%22%3A%22USD%22%2C%22timeout%22%3A60000%2C%22publicKey%22%3A%22sjc-bpUMSczM3JXCvbPodSbPac%22%2C%22parent%22%3Atrue%2C%22cors%22%3Afalse%2C%22api%22%3A%22https%3A%2F%2Fapi.recurly.com%2Fjs%2Fv1%22%2C%22style%22%3A%7B%7D%2C%22fields%22%3A%7B%22number%22%3A%22%5Bdata-recurly%3Dnumber%5D%22%2C%22month%22%3A%22%5Bdata-recurly%3Dmonth%5D%22%2C%22year%22%3A%22%5Bdata-recurly%3Dyear%5D%22%2C%22cvv%22%3A%22%5Bdata-recurly%3Dcvv%5D%22%7D%2C%22required%22%3A%5B%5D%7D%7D" border="0" frameborder="0" allowtransparency="true" scrolling="no" style="height: 100%; width: 100%; background: transparent;">
          </iframe>
        </div>
      </div>
      <div data-recurly="cvv">
        <div class="recurly-hosted-field recurly-hosted-field-cvv">
          <iframe src="https://api.recurly.com/js/v1/field?config=%7B%22type%22%3A%22cvv%22%2C%22selector%22%3A%22%5Bdata-recurly%3Dcvv%5D%22%2C%22style%22%3A%7B%7D%2C%22recurly%22%3A%7B%22currency%22%3A%22USD%22%2C%22timeout%22%3A60000%2C%22publicKey%22%3A%22sjc-bpUMSczM3JXCvbPodSbPac%22%2C%22parent%22%3Atrue%2C%22cors%22%3Afalse%2C%22api%22%3A%22https%3A%2F%2Fapi.recurly.com%2Fjs%2Fv1%22%2C%22style%22%3A%7B%7D%2C%22fields%22%3A%7B%22number%22%3A%22%5Bdata-recurly%3Dnumber%5D%22%2C%22month%22%3A%22%5Bdata-recurly%3Dmonth%5D%22%2C%22year%22%3A%22%5Bdata-recurly%3Dyear%5D%22%2C%22cvv%22%3A%22%5Bdata-recurly%3Dcvv%5D%22%7D%2C%22required%22%3A%5B%5D%7D%7D" border="0" frameborder="0" allowtransparency="true" scrolling="no" style="height: 100%; width: 100%; background: transparent;">
          </iframe>
        </div>
      </div>
      <input type="hidden" name="recurly-token" data-recurly="token">
      <button>submit</button>
    </form>
    <script src="https://js.recurly.com/v4/recurly.js"></script>
    <script>
      recurly.configure('sjc-bpUMSczM3JXCvbPodSbPac');
    </script>
  </body>
</html>
```

Don't worry about my API key being public, I already requested a new one.

**Comment by frewsxcv** [comment]
No errors appear in the console. This code is [taken straight from the "Getting Started" section in the documentation](https://dev.recurly.com/docs/getting-started-1).

**Comment by chrissrogers** [comment]
Hey! The default behavior for the injected iframes is to expand to the full size of their containers. So your form fields are there, they just don't look like form fields yet.

See the section regarding [form styling](https://dev.recurly.com/docs/getting-started-1#section-styling-card-fields) for more detail on how to style your fields to look like form inputs.

No errors in the console is great -- everything is working as expected.

**Comment by frewsxcv** [comment]
> The default behavior for the injected iframes is to expand to the full size of their containers.

Is there any reason why this is the default behavior? I imagine the first usage example in the documentation should be of a *working* example. What do you think?

**Comment by chrissrogers** [comment]
It is working, it just doesn't look like a form field until it's styled to look like one.

The behavior of expanding to the full size of the container is such that it will respect whatever styling you give the container.

**Comment by frewsxcv** [comment]
>  It is working

Alright, if you say say so, because to me, it looks like it's not working. It might have been helpful if the documentation mentioned something about styling at that point.

--------

Also, what does the `fields` key in this object do in this example? It's not mentioned anywhere. https://dev.recurly.com/docs/getting-started-1#section-styling-card-fields

---------

Also, I tried to submit a payment with this form. The fields were empty. This is the error that returned from the server:

<img width="391" alt="screen shot 2016-04-20 at 4 04 46 pm" src="https://cloud.githubusercontent.com/assets/416575/14688651/afae4b2e-0711-11e6-84c3-750b44c2cd8f.png">

> "There was an error validating your request."

What does this error message mean? Am I missing data fields? It seems very vauge.

**Comment by chrissrogers** [comment]
There's a good overview of what certain errors mean [in the docs](https://dev.recurly.com/docs/errors-1), which will give you the best idea of how to handle error states.

The specific error you are referencing shows that those five fields are invalid, which matches to what you were saying about submitting the fields blank.

**Comment by frewsxcv** [comment]
> The specific error you are referencing shows that those five fields are invalid, which matches to what you were saying about submitting the fields blank.

Well now I'm putting in real data, but it says the "month" and "year" fields are still problematic with the same `code` and `message` as the screenshot I linked above. Is there no way to get a more helpful error message? Something that describes the problem with the inputted data?

**Comment by chrissrogers** [comment]
What are the values of month and year?

**Comment by frewsxcv** [comment]
I just realized I was putting in "3" and "16" respectively, but I'm not realizing that was last month. It'd be helpful if the error message indicated the card expired or something. My bad though

**Comment by chrissrogers** [comment]
Ahh gotcha. Yeah I'm with you on improving the error indications across the board. Right now they are not meant to be displayed as customer messages, and I think it would be great if they were.
