### ISSUE TITLE
Placeholder font color does not get set in chrome

### ISSUE THREAD

**Issue by implausible** [recurly/recurly-js#252]
In hosted fields in chrome, when setting the fontColor of a hosted-field in the configuration object being passed to Recurly, the hosted field's placeholder fontColor does not change.

As an example, if you were to pass in the object

```JS
{
  publicKey: API_KEY_HERE,
  style: {
    number: {
      fontColor: 'red',
      placeholder: '####-####-####-####'
    }
  }
}
```

To recurly using `recurly.configure`, the iframe which holds the input inside of `<div data-recurly='number'></div>` will change the input text to font color red, but the placeholder font color will still be default.

**Comment by chrissrogers** [comment]
hey @implausible -- we don't currently support this, but I don't see a reason not to add placeholder colorization. I all of our supported browsers support this via vendor prefixing.

**Comment by chrissrogers** [comment]
This will go out in the next release

**Comment by bbowler001** [comment]
@chrissrogers can you confirm that this has, in fact, made it's way out in the world? cc'in @jss79 @KristaBaker

**Comment by chrissrogers** [comment]
Not quite yet @bbowler001

**Comment by DaPo** [comment]
Hi @chrissrogers, still have this issue. Do you have any workaround?

Thanks!

**Comment by chrissrogers** [comment]
@DaPo can you provide the operating system and browser on which you're seeing the issue?
