### ISSUE TITLE
Configuring tax with recurly.Pricing()

### ISSUE THREAD

**Issue by vojtech-dobes** [recurly/recurly-js#259]
Hi, could someone please clarify how `recurly.Pricing()` should be used to include taxes? I unfortunately cannot find it in documentation.

We don't use `attach` because we want to use this API to calculate several different price combinations at once and show them side by side (user then just picks the combination). We would like to calculate tax for each combination as well (if applicable), but how should we configure `recurly.Pricing()` object to achieve that? So far we use only `plan`, `currency` and `addon` methods.

**Comment by chrissrogers** [comment]
Sure thing. Given the country, postal code, and tax code provided to the Pricing API, it will compute an estimated tax amount onto your pricing structure. The required fields depend a lot on what taxes you are configured to charge your customers. At a minimum, country is needed.

**Comment by vojtech-dobes** [comment]
Thanks for answer! Could you please post example code of the relevant call on `recurly.Pricing()`?

**Comment by chrissrogers** [comment]
The best example of this in use is in the docs [here](https://dev.recurly.com/docs/pricing#section-pricing-api), specifically where it shows the call to `address` and `tax`.

**Comment by vojtech-dobes** [comment]
Damn, I completely missed it, couldn't find it there at first. Thanks once again for answer.

**Comment by chrissrogers** [comment]
No problem! Here to help :)
