### ISSUE TITLE
Set CSS padding via recurly.configure()

### ISSUE THREAD

**Issue by MichaelFromin** [recurly/recurly-js#260]
I need to use recurly.js on a purchase form that is styled with Bootstrap.  The Bootstrap form fields set padding on input fields so that the text is not flush to the edge of the field.  I have tried this in my configure() method:  

``` 
recurly.configure({
				publicKey: 'xxx-xxxxxxxxxxxxxxxxxxx',
				style: {
					all: {
						fontFamily: 'Verdana',
						fontSize: '14px',
						fontWeight: 'normal',
						padding: '8px'
					},
					number: {
						placeholder: 'Credit card number'
					},
					month: {
						placeholder: 'Exp. Month (mm)'
					},
					year: {
						placeholder: 'Exp. Year (yy)'
					}
				}
});
```

...but the **padding** option appears to simply be ignored.  How can I inject padding into the input fields in the iFramed credit card fields?

Note in this screenshot that the credit card fields have no padding whereas the billing fields do:
![screen shot 2016-06-02 at 8 12 33 am](https://cloud.githubusercontent.com/assets/12281396/15747841/cdd333a4-2899-11e6-9b76-abda97929971.png)

**Comment by chrissrogers** [comment]
padding is not currently among the css properties that can be passed into field configuration, **but** you can specify it on the field container style to achieve the result you're looking for. Simply add padding to the `.recurly-hosted-field` class.

**Comment by qualidafial** [comment]
Putting the padding on the `.recurly-hosted-field` tag in the host frame, removes the ability to focus the field by clicking in the padding.

**Comment by chrissrogers** [comment]
Good point @qualidafial. I think the solution here is to delegate any click and focus events that occur on the container elements to trigger focus within the fields.

**Comment by qualidafial** [comment]
I guess I'm confused as to why padding is not supported. Is there a security reason for this restriction?

**Comment by chrissrogers** [comment]
No security issue. We just wanted as much of the look and feel of the fields to be specified in the field classes, since passing css values into configuration isn't ideal.

**Comment by qualidafial** [comment]
If that's the case, would you consider reopening this issue? I view this as a usability issue, particularly on mobile.

**Comment by chrissrogers** [comment]
@MichaelFromin @qualidafial 

Between these two options, which would be a better solution for you guys?

**Comment by MichaelFromin** [comment]
For my use case I just need to pass the padding into the configure call.

**Comment by qualidafial** [comment]
I'd prefer padding as well.

**Comment by chrissrogers** [comment]
Cool! I'll be adding both, but will prioritize padding support in the configure call. Thanks for the input from both of you.

**Comment by chrissrogers** [comment]
Just so you gents are up to date, The code change for this is ready and will go out with the next version of the library that runs within the hosted fields. I'll put a note here once that's happened.

**Comment by mharis** [comment]
I needed this as well, great timing!

**Comment by remacg** [comment]
+1.  Please add padding.

**Comment by chrissrogers** [comment]
This is now available in production. Enjoy! And thanks for working with me on this to figure out the best solution!

[Documentation here](https://dev.recurly.com/docs/getting-started-1#section-styling-card-fields)

**Comment by beaubarbour** [comment]
I can't find anything in the documentation link provided above.  Can someone provide a link to a solution for the padding issue?

**Comment by chrissrogers** [comment]
@beaubarbour quite! It looks like the padding reference disappeared. Check it now, as I've restored it.
