### ISSUE TITLE
Event/Promise when pricing.attach() is complete?

### ISSUE THREAD

**Issue by mfromin** [recurly/recurly-js#270]
I have a scenario where I have two plan that are identical except that one is billed monthly and one is billed annually.  

If you switch between the two plans I need to "remember" what addons you had selected in the plan.  I have code to do all of this and its working well except for one thing... I have no way to know when the `pricing.attach()` call completes after the plan changes.  

In order to trigger recurly to recalculate the price after plan is changed  I have code that "clicks" the checkboxes - and this forces the recurly JS to properly recalculate the plan price.

As a workaround I have used `setTimeout()` to delay my code that resets the checkboxes but it would be better if I could get some type of notification when the `attach()` stuff is done.

_Note: I opened a support case and the support folks told me to open an issue here._

**Comment by chrissrogers** [comment]
If I understand correctly, it sounds like you would like to know when your addons have been re-added to the price after a plan change. You could listen for the `set.addon` event on your `Pricing` instance until you receive a number of calls equal to the previous total of addons selected.

If you have any sample code, in a gist even, that could help me understand the need more ⚡

**Comment by MichaelFromin** [comment]
Chris - 

I made this gist to show you the crux of the code:  

https://gist.github.com/MichaelFromin/3ffabfb5e6dd5173ad82d0f54191084e

I did not provide the entire JavaScript as its over 250 total lines and much of it is not relevant to this issue.  If the code is not clear let me know.

**Comment by chrissrogers** [comment]
Ah great, yes that is very helpful. So you're looking for a way to know once the `attach` method has finished attaching listeners to the form, so that you can trigger changes on the form that the `Pricing` instance will react to.

**Comment by MichaelFromin** [comment]
@chrissrogers

Exactly!

**Comment by chrissrogers** [comment]
@MichaelFromin Sorry that this has taken me so long to build, but this event is coming soon :)
