### ISSUE TITLE
Onchange event crashes browser

### ISSUE THREAD

**Issue by mharis** [recurly/recurly-js#280]
Onchange event is triggered multiple times when making one change.

I'm using onchange to detect card type and add a small card logo over the card number field but it crashes the browser as the user inputs the full credit card number. The on change event seems to be triggered multiple times.

- On page load, recurly on change is triggered once
- I enter "4" into the number field and the recurly onchange is triggered 4 times
- I enter "1" into the number field and the recurly onchange is now triggered 8 times in total
- I enter another "1" and now the recurly onchange event is now triggered 16 times in total

Is this a known issue? I'm integrating recurly within a react app.

**Comment by chrissrogers** [comment]
We haven't seen this occur before with Recurly.js on its own, no. It would appear the events are being rebound on each consecutive input, which is abnormal. Would you mind creating a gist that demonstrates this behavior?

**Comment by chrissrogers** [comment]
Closing this for now. If anything resurfaces, We'd love to hear about it.
