### ISSUE TITLE
Allow setting textAlign via recurly.configure()

### ISSUE THREAD

**Issue by remacg** [recurly/recurly-js#281]
Request allowing the CSS text-align property for hosted fields to be set via recurly.configure(), like:

```
	recurly.configure({
		publicKey: 'RECURLY_KEY',				
		style: {
			cvv: {
				textAlign: 'center',
			},
		}
	});
```

Checkout form designers often like to center text in CVV and month/year inputs fields.  Adding textAlign would help with that considerably.

**Comment by chrissrogers** [comment]
Sure, I'd be happy to add that in.

**Comment by chrissrogers** [comment]
Closing was a result of adding the feature into the field handling code. I expect it will go out later this week, and will update you here when it does.

**Comment by chrissrogers** [comment]
Hi! This has been published. Feel free to set `textAlign` as you see fit.
