### ISSUE TITLE
Official NodeJS client

### ISSUE THREAD

**Issue by mharis** [recurly/recurly-js#284]
Hey guys,

Right now, there is no official nodejs client available which is being maintained. Most of them are hugely outdated.

Are there any plans of Recurly to start such a project.

Thanks!

**Comment by chrissrogers** [comment]
Hey @mharis -- we don't currently have any plans to build an official node.js client for our v2 API. I'd suggest taking a look at robrighter/node-recurly. I've used it and think it's quite nice and simple.  It looks like it might be missing some newer endpoints (addon usage, measured units, invoice refunds, etc.) I think those would be quite simple to add if needed.
