### ISSUE TITLE
'field:submit' event is not emitted when the enter key is pressed on a hosted field

### ISSUE THREAD

**Issue by r4ngy4l** [recurly/recurly-js#285]
**To Reproduce**
1. Open [this fiddle](https://jsfiddle.net/robertonline/28y9z1s7/)
2. Click into a hosted field
3. Press 'Enter' key

**Expected behavior**
The `field:submit` event should be emitted.

**Actual behavior**
The `field:submit` event is not emitted. - 'field:submit' is not logged to the console.

**Comment by chrissrogers** [comment]
Good catch, thank you. A patch has been created and will go out with `v4.1.1`

**Comment by chrissrogers** [comment]
This was closed due to the feature being merged into master on the field internals. Please look for this in the next version.
