### ISSUE TITLE
Support web fonts sourced from anywhere for hosted fields

### ISSUE THREAD

**Issue by r4ngy4l** [recurly/recurly-js#286]
It would be nice to apply web fonts sourced from anywhere to hosted fields, not just Google Web Fonts.

**Comment by chrissrogers** [comment]
Our security policies are quite strict around outside scripts, resources, etc -- especially within the hosted fields. Since Google is one of the few vendors we trust, and only one that provides web fonts, we currently only allow custom web fonts to load through them.
