### ISSUE TITLE
Generic font family is requested from Google Web Fonts

### ISSUE THREAD

**Issue by r4ngy4l** [recurly/recurly-js#289]
**To Reproduce**

1. Set a generic font (e.g. sans-serif) for a hosted field
2. See the request sent to fonts.googleapis.com by hosted-field.js

Please find an example here: https://jsfiddle.net/r4ngy4l/28y9z1s7/

**Comment by chrissrogers** [comment]
Thanks for the fiddle demonstration! Imo that is an okay side-effect. A font lookup that comes 404s is not a huge burden, and the browser will certainly display the font properly.
