### ISSUE TITLE
Hosted fields should force numbers-only for ALL browsers

### ISSUE THREAD

**Issue by cyruscollier** [recurly/recurly-js#290]
There is no reason for any of the generated hosted fields to contain anything other than numbers. The existing implementation only forces a numeric keyboard for iOS, but Android and all desktop browser (as far as I know) ignore the `pattern` attribute and still allow any character. Here is what I propose for the fields:
### HTML:

(Note the pattern change from `\d*` to `[0-9]*` which has been reported to have better cross-browser support.)

```
<input type="number" pattern="[0-9]*" inputmode="numeric" maxlength="16"> <!-- card number -->
<input type="number" pattern="[0-9]*" inputmode="numeric" maxlength="2"> <!-- exp. month -->
<input type="number" pattern="[0-9]*" inputmode="numeric" maxlength="2"> <!-- exp. year -->
<input type="number" pattern="[0-9]*" inputmode="numeric" maxlength="4"> <!-- cvv -->


```
### CSS:

(Removes the arrows on the number fields in Webkit and Firefox)

```
input[type='number'] {
    -moz-appearance:textfield;
}

input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
    -webkit-appearance: none;
}
```

**Comment by chrissrogers** [comment]
Good suggestions. The maxlengths would need to be modified for some edge cases, but I generally agree that suggesting numeric input is a good idea.

The card number field should ideally allow pasting of dashes and spaces, with coercion of the pasted input into a pure number.

Thoughts on the above?

**Comment by cyruscollier** [comment]
Allowing for dashes and spaces would be nice. However, if we don't have `type="number"` then iOS and Android won't show the numeric-only keyboard, which I think is a better UX benefit than dashes and spaces, in my opinion. If there was a clean and reliable way to serve a number field to mobile and a text field with a formatting mask for dashes or spaces to desktop, that would be ideal, but that might not be worth the trouble.

**Comment by chrissrogers** [comment]
Varying the type by browser type may work to all advantages. Mobile users of android would be subject to `<input type="number">` enforcement, but other browsers would not be constrained in the same way.

**Comment by cyruscollier** [comment]
Agreed, although I would hope that could be done with feature detection and not user-agent sniffing. Since adding a validation/formatting mask is really a separate feature and more involved, why don't we implement this feature now for every browser and make the mask a separate enhancement? Then removing the number type for browsers that don't need it can be a part of that feature branch.

**Comment by chrissrogers** [comment]
The problem with the `number` type is that it doesn't really apply to codes such as credit card numbers and cvc values. Those are best classified as text values.

So if it's necessary to add `type="number"` to get the numeric keypad on Android, then the hack should be as limited in scope as possible.

For the other advantages of the `number` type like being able to only input numbers, I think Javascript input scrubbers are well suited to that purpose.

**Comment by R3VoLuT1OneR** [comment]
@chrissrogers What's going on with the issue?
Numeric keyboard not triggered on Android devices.

Can I do some hack by myself to make it work?

**Comment by chrissrogers** [comment]
@R3VoLuT1OneR you won't be able to hack it unfortunately, as there's no way to affect the contents of the hosted field iframes.

I don't have any plans to add support for this since from our previous discussion it appears we'd need to use `type="number"` to achieve the numeric keypad.. but it's not really the appropriate field type here. Would be happy to add support if there was a way to get the keypad without using the number field type.

**Comment by R3VoLuT1OneR** [comment]
@chrissrogers Why not use `type="tel"`? It works for us on different payment solution. Braintree using also `type="tel" pattern="[0-9]*"`and actually this is the solution for the problem I think.

Even if this is not the solution, it is not UX benefit, it is UX  pattern="[0-9]*" in 2017.
Issue affects customers conversion rates.

**Comment by chrissrogers** [comment]
@R3VoLuT1OneR I'll do some investigation and testing.. but looks promising. Thanks for following up.

**Comment by chrissrogers** [comment]
Just a heads up that we'll be incorporating this into the next internal release of our hosted fields backend. I don't have an exact timeline, but stay tuned.
