### ISSUE TITLE
Recurly returns a token when the credit card is valid and cvv is not present

### ISSUE THREAD

**Issue by bholtbholt** [recurly/recurly-js#291]
When I fill my credit card details **without the cvv** as follows:
```
number: 4111 1111 1111 1111
month: 02
year: 2020
```
and use this javascript:
```
$('form').on('submit', function (event) {
  var form = this;
  event.preventDefault();
  recurly.token(form, function (err, token) {
    if (err) {
      // handle error using err.code and err.fields
    } else {
      // recurly.js has filled in the 'token' field, so now we can submit the
      // form to your server; alternatively, you can access token.id and do
      // any processing you wish
      form.submit();
    }
  });
});
```

Recurly returns a `token`, and `err === null`.

Without a CVV I should not get a token and `err` should return an error on either the `number` or `cvv` field.

**Comment by chrissrogers** [comment]
It's actually possible to charge a credit card under certain circumstances without the cvv. This largely depends on your gateway configuration.

If you would like to specifically require the cvv, then you may use the following in your configuration.

```js
recurly.configure({
  // ..
  required: ['cvv']
  // ...
});
```

**Comment by jdaly13** [comment]
Not sure why this isn't in their documentation

**Comment by khousuylong** [comment]
Thanks man. it works

**Comment by yevhen-logosha** [comment]
guys is it possible to similarly configure it in React-recurly ?

**Comment by yevhen-logosha** [comment]
Answering my question two years later 🙈 
Yes, it is, via provider's require option, see https://recurly.github.io/react-recurly/?path=/docs/components-recurlyprovider--page
