### ISSUE TITLE
Display validation messages next to hosted fields

### ISSUE THREAD

**Issue by kumaro** [recurly/recurly-js#292]
on recurlyJS validation error, Need to display a message like "Card Number can't be blank" next to Hosted Iframe card number input field  . Any idea how to display this and clear it when the user starts typing the number ?

**Comment by chrissrogers** [comment]
I suggest listening to the `change` event as follows.

```js
recurly.on('change', state => {
  // state.fields.number.empty;
});
```

**Comment by kumaro** [comment]
That works. Thanks for the prompt reply
