### ISSUE TITLE
User-facing validation messages

### ISSUE THREAD

**Issue by r4ngy4l** [recurly/recurly-js#294]
It would be nice to show user friendly error messages for invalid fields, but currently there is no way to identify why the validation failed (eg. the field is required, its value should be 3 characters long - cvv, etc...) for a hosted field. Nor the state nor the error event object contains any info, that could be used to display a user friendly validation message.

**Comment by chrissrogers** [comment]
+1 I had this as a nice to have on #129 -- glad to have your request here too. It's definitely something we'd like to add. Closing this in favor of that issue.

I'd like to allow for an i18n map to be passed to recurly.js and a host of error codes for each error scenario.
