### ISSUE TITLE
Option to show paypal in a popup window (instead of a new tab)

### ISSUE THREAD

**Issue by gregsabo** [recurly/recurly-js#296]
By default, calling `recurly.paypal` opens the paypal flow in a new tab. I'd like to have the option to display paypal as a smaller "popup" window on top of the current tab. This could be surfaced in an option like `popup: true`, perhaps.

I believe that [these two TODOs](https://github.com/recurly/recurly-js/blob/master/lib/recurly/open.js#L20-L21) in the code reference the same feature.

**Comment by chrissrogers** [comment]
Yep! That's exactly what the TODOs would support.

I think this is called for, certainly. Good suggestion.

We're accepting patches if you want it in quickly ;)

**Comment by chrissrogers** [comment]
This is in v4.3.0+

**Comment by johan44co** [comment]
How can we actually use this pop-up feature for Paypal?
