### ISSUE TITLE
Support for Amazon Payments

### ISSUE THREAD

**Issue by geetotes** [recurly/recurly-js#304]
Does recurly.js support Amazon Payments? The [documentation](https://docs.recurly.com/docs/amazon-payments) on Amazon Payments says that it is supported in versions 3 and 4, but I can't find any documentation in the recurly.js docs.

**Comment by chrissrogers** [comment]
@geetotes sorry, the documentation is a little confusing. I'll be sure it's updated soon.

Recurly.js is not required to implement Amazon Payments. We provide a [helper library](https://github.com/recurly/pay-with-amazon) to make using it a bit easier, though, which is what the technical parts of that document highlight.

Happy to assist with any other questions you have.
