### ISSUE TITLE
[4.3.0] Card fields invisible

### ISSUE THREAD

**Issue by vysinsky** [recurly/recurly-js#305]
Hi,

after upgrade to version 4.3.0 fields for credit card became invisible. It was ok with version 4.2.0. No errors in console

![image](https://cloud.githubusercontent.com/assets/3693578/20590304/9f389a94-b222-11e6-9c57-dcda992773cb.png)

Whole div.recurly-hosted-field.recurly-hosted-field-number is missing:

Version 4.2.0:
```html
<div data-recurly="number">
	<div class="recurly-hosted-field recurly-hosted-field-number">
		<iframe src="" border="0" frameborder="0" allowtransparency="true" scrolling="no" style="height: 100%; width: 100%; background: transparent;">
        </iframe>
	</div>
</div>
```

Version 4.3.0:
```html
<div data-recurly="number"></div>
```

**Comment by chrissrogers** [comment]
@vysinsky do you still see this issue? Can you provide a URL to demonstrate this error?

**Comment by vysinsky** [comment]
I am sorry for false alarm. We hit this problem in previous version: https://github.com/recurly/recurly-js/issues/253 so we put `recurly.readyState = 0` to our code. After update it is not needed and it actually broke the fields. With Recurly 4.3.0 and removed `recurly.readyState` line it works perfectly. Thanks for your time I am closing this issue.

**Comment by chrissrogers** [comment]
Ah! Great, thank you for the heads up. I'll put a note in the other issue for anyone else that may have implemented the same workaround. Cheers!
