### ISSUE TITLE
Cannot read property 'number' of undefined

### ISSUE THREAD

**Issue by joneslloyd** [recurly/recurly-js#309]
Hi there,

Even though Recurly is successfully injecting its iframe code for Expiry Month, Expiry Year, CVV and Credit Card Number (observable by clicking Inspect in Chrome), upon submission, the following JS console error appears:

![screen shot 2017-01-11 at 14 08 36](https://cloud.githubusercontent.com/assets/997427/21849751/a7ece20c-d807-11e6-9b28-9e7b7dd2891f.png)

Do you know why that may be? This happens regardless of whether the Credit Card Number field has anything entered into it (or not) at the time of form submission.

**Comment by chrissrogers** [comment]
Hmm unfortunately it's not enough to go on. If you click the link `recurly.js?ver=1.0.0:7` it will take you to the point in code that originated the error, which may be helpful. Do you have a link as well to your implementation in progress?

**Comment by joneslloyd** [comment]
@chrissrogers That point in the code (once unminified by Chrome dev tools) is this:
![screen shot 2017-01-12 at 10 47 55](https://cloud.githubusercontent.com/assets/997427/21884686/aa6db878-d8b4-11e6-8eaf-7535ccf1cc42.png)

You can see the issue here, if you click "Submit": http://gfrecurly.onpressidium.com/payment/

**Comment by chrissrogers** [comment]
Thanks for the detail @joneslloyd -- I'll look into this further and see if I can suss the bug out

**Comment by joneslloyd** [comment]
No problem! I've actually solved the above now, in the past few minutes weirdly! (I'd overlooked a variable declaration).

However, I'm now noticing that the error thrown / returned by the API is
```
{
code: "validation",
fields: [
  0: "number",
  1: "month",
  2: "year",
  3: "first_name",
  4: "last_name",
  5: "cvv"
]
message: "There was an error validating your request.",
name: "validation"
}
```

Even when I enter a real (but expired) credit card number, all fields are marked invalid (I would have that that at least `number` would be okay doing that?)

**Comment by joneslloyd** [comment]
In fact, I just entered card details for an active credit card (Number, Expiry, Month, Year, CVV) and the same error was also returned.

**Comment by chrissrogers** [comment]
Can you verify that the request being sent to the `token` endpoint contains your card data?

**Comment by joneslloyd** [comment]
Actually, it doesn't seem to - I'm guessing it could be because my Number, Expiry, Month, Year and CVV fields are `input`s rather than `div`s?

It doesn't seem to have any problem injecting the Recurly code inside an input though:
![screen shot 2017-01-13 at 20 06 53](https://cloud.githubusercontent.com/assets/997427/21942092/e01bad1e-d9cb-11e6-8868-63f0eb45b612.png)

If the issue is because of this, is it possible to allow `input` field types?

**Comment by chrissrogers** [comment]
Possibly, but I doubt it. Would you mind putting your form handling and tokenization code into a gist?

**Comment by joneslloyd** [comment]
No problem - Here you go:

https://gist.github.com/joneslloyd/f6754fd7d6616ab93080ca8eb210f07e

(I am logging the Recurly response error to the console)

**Comment by chrissrogers** [comment]
I would suggest checking [this line here](https://gist.github.com/joneslloyd/f6754fd7d6616ab93080ca8eb210f07e#file-frontend-js-L60) to see if it is identifying the correct form

**Comment by joneslloyd** [comment]
It is correctly identifying the form. If I add a `console.log` here:
```
console.log( $( '#gform_' + GFRecurlyObj.formId )[ 0 ] );
recurly.token( $( '#gform_' + GFRecurlyObj.formId )[ 0 ], function ( err, token ) {
  GFRecurlyObj.responseHandler( err, token );
} );
```

It prints the following to the console, which, when I mouseover, highlights the correct form:
![screen shot 2017-01-13 at 21 16 15](https://cloud.githubusercontent.com/assets/997427/21944292/a7c93706-d9d5-11e6-850b-9b887617a23b.png)

**Comment by joneslloyd** [comment]
Just for your information: There was an update to the Recurly API repository that I added to my codebase, but this doesn't seem to have helped. The issue above still stands.

**Comment by chrissrogers** [comment]
Just had a chance to look through your page. It's as you suspected -- the input fields are not displaying the hosted fields. You'll need to use container elements of some sort, like a div, instead of an input element. When you're typing on that page, you're typing into the input element and not the actual hosted field, thus recurly.js does not know about the card values.

![](https://cldup.com/puWcxMPi2k.png)

**Comment by joneslloyd** [comment]
Hi @chrissrogers - Thanks!

I thought that could be the case, but interestingly/oddly when I Inspect in Chrome on the example, the original (not injected) inputs are there in the DOM and receive the input: https://kale-krate.herokuapp.com/subscribe-minimal

**Comment by chrissrogers** [comment]
Mm yes, thanks for pointing to that. The kale krate example has been retired as it only demonstrated Recurly.js v3, thus the injected fields are not present as they were added in v4. It's no longer referenced in the documentation, but I will have to take down the heroku  app soon too. Sorry for the confusion.

**Comment by chrissrogers** [comment]
Heads up that I just took it offline :]

**Comment by joneslloyd** [comment]
Got it! Okay!

I wonder (in that case) if Recurly JS is right for me / my solution, as what I'm using (Gravity Forms) has a load of built-in listeners and validators that rely on the inputs being unchanged (at least to the degree where they change from inputs to divs).

I probably know the answer already, but worth asking:
Is there any way you can add something to accommodate users who would like to use Recurly JS for compliance reasons, but are limited by the functional requirements of their setup in having to use inputs?

I wonder if having the injected DIVs hidden, and being updated on each keypress into the existing inputs on the page would work....

**Comment by chrissrogers** [comment]
Unfortunately the limitation is precisely compliance. Under PCI, the merchant (yourself) mustn't have direct access to customer credit card data. The provider (Recurly) has to accept the brunt of the PCI compliance requirements, thus we need to isolate that customer data.

While we can't adapt to every form library out of the box, I think you may be able to build a connector if you must use a certain form library. Recurly.js emits a bunch of data about form field state on the 'change' event.

But moreover, I think the best solution is to not use the form library for the customer's card data. With a bit of CSS, you could achieve an exact look and feel that matches the appearance of your other form fields. I think your customer experience could be exactly as it is -- don't see any limitations there.

**Comment by joneslloyd** [comment]
@chrissrogers Thanks for the info!

Are these events documented? And which object am I listening to, just the `recurly` one itself?

**Comment by chrissrogers** [comment]
Yep, you'd listed by doing something like the following

```js
recurly.on('change', function (state) {
  // check state.fields
});
```

Check out the [docs here](https://dev.recurly.com/docs/events)

**Comment by joneslloyd** [comment]
Cheers

**Comment by joneslloyd** [comment]
Hi @chrissrogers -- Sorry, I've realised that due to cross-domain iframe rules, I can't do something like this for the credit card number:
- Have my original input visible, and the Recurly credit card number div hidden
- onChange of my input, find the iframe in the Recurly c.c. number div, and then find the input child element
- Update the input child element with my value

Is it possible to achieve this any other way? ie, pass the credit card number to the recurly JS object, etc.?

**Comment by chrissrogers** [comment]
Unfortunately it wouldn't be possible. The intent of the iframe is to restrict your page from ever accessing the credit card number, thus fulfilling the PCI SAQ-A requirements. Accepting card data in the manner you're describing would unfortunately not comply. I definitely recommend you accept customer card data directly via the hosted fields.

**Comment by joneslloyd** [comment]
Got it, okay!

I'll proceed without Recurly JS for now, but if it's possible, one day, to use `input` elements as well as `div`s, I can jump back in and use it.

Thanks for your help!
