### ISSUE TITLE
Recurly 4.3.0 broken reinitialize: visibility:hidden on fields afterwards

### ISSUE THREAD

**Issue by Routhinator** [recurly/recurly-js#311]
We developed a pricing page against a pre 4.3.0 version where CC fields were set to display: none when the use chose banking. 

When the user switched back to CC, we would set readyState to 0 and reconfigure to get the CC fields to reinitialize.

```
recurly.readyState = 0;
recurly.configure(recurlyConfig);
```

This worked. Now 4.3.0 is supposed to do the same without the need to set the readyState.. and it sort of is.. however the fields in the iframe have `visibility: hidden` on them after Recurly reinitializes, leaving the form broken for the user. 

Using chrome inspector I can remove the `visibility: hidden` from the fields manually and I can see the form works and the fields are otherwise initialized properly. 

Why is `visibility:hidden` being added? It's either a bug, or we need to recode how we're reinitializing the fields for 4.3.0 - but I cannot find relevant information on this.

**Comment by Routhinator** [comment]
![screenshot from 2017-01-16 13 12 29](https://cloud.githubusercontent.com/assets/727535/21999144/8230954c-dbed-11e6-9f5e-dc48c509e990.png)

**Comment by chrissrogers** [comment]
The hidden style is removed once initialization is complete, so this leads me to believe that something is halting initialization for you. Do you have a live payment form that I can access to see what might be the issue?

**Comment by chrissrogers** [comment]
I'm going to close this for now -- please reopen if the issue persists!
