### ISSUE TITLE
 Tokenization error by recurly.token is not user friendly 

### ISSUE THREAD

**Issue by railsstudent** [recurly/recurly-js#316]
The error message returned by recurly.token function is too technical and not user-friendly for our QAs to understand.  Please advise if there is complete error list such that I can use code and field to do our own customisation.

For example, if I input 4-digit CVV and validation fails the error message is 
{
code: 'invalid-parameter',
fields:  [ "cvv"],
message: "Cvv ["must be three digits"]"
name: "api-error"
}
Can message Cvv ["must be three digits"] return without the enclosing []?

If credit card year, postal code and cvv fail the validation, the errors are concatenated to the message
{
code: 'invalid-parameter',
fields:  [ "year", "cvv", "postal_code"],
message: "Year must be less than 2050, Cvv ["must be three digits"] and Postal code ["not valid"]"
name: "api-error"
}
The meaning for year and Cvv is very clear but postal code ["not valid"] is too generic. QA understands wrong postal code is inputted but not sure what causes it.   

Is there a full error list such that I can do our won customisation. Furthermore, our app supports multilingual, I wish to do our customisation to display error message in Chinese and other languages.

**Comment by jchayan** [comment]
Same problem here. The error message format is terrible, you could instead return both the fieldName and the errorMessage as an object pushed to the fields array.

**Comment by railsstudent** [comment]
That was the original implementation but QA logged issue that the [] in the error message is necessary and want it removed.  
For this case, I can do it but I am not sure if there are other error formats waiting to creep up in the future.
I prefer to have the error handing function to be as generic as possible in front-end where I am responsible for.

**Comment by jchayan** [comment]
However, recurlyjs documentation states that message is not intended for front-end error handling, instead it is recommended to have your own error messages to display to the users, abd should be based on the error code received. However, I think that it would be a great improvement to enable these messages to be used for displaying errors. It just needs a better formatting.

**Comment by chrissrogers** [comment]
I definitely agree that it would be nice to have user-facing error messages. We don't have a timeline at the moment, but It's on the horizon :)
