### ISSUE TITLE
Bug: Year field format is two digits, but it allows the user to input four digits

### ISSUE THREAD

**Issue by jchayan** [recurly/recurly-js#323]
This should not happen at all, is there any configuration I can pass to the field to limit the user's input to 2 digits?

**Comment by chrissrogers** [comment]
Hi @jchayan -- could you elaborate on the field format constraint of two digits that you're referring to? We aim to support both 2 and 4-digit year values across the board.

If you're wishing to restrict the input to 2 digits, we don't explicitly support that configuration currently. We decided to allow year formats up to 4 digits in case customers wanted to input that way.

**Comment by jchayan** [comment]
Yes @chrissrogers sorry, I misunderstood the API documentation. Thought it was required to input only 2 digits. Thank you

**Comment by chrissrogers** [comment]
Understood!
