### ISSUE TITLE
Bug: Recurly returns random 302 responses

### ISSUE THREAD

**Issue by jchayan** [recurly/recurly-js#324]
I can't seem to reproduce this issue with a series of steps but, What I have replicated is that on random requests (very random), the API call to 'token' (using recurly.token) returns a 302 (FOUND) response. Then if you try to make the request again, it succeeds. Can anyone tell me on what scenarios I can get this response and how to handle it? Here I attach a proof, using a simple form on chrome:

<img width="1280" alt="302-2" src="https://cloud.githubusercontent.com/assets/8838243/22898339/8ced4a4c-f1ec-11e6-985c-f4ef52f2483a.png">

<img width="1280" alt="302-1" src="https://cloud.githubusercontent.com/assets/8838243/22898341/91a8cfde-f1ec-11e6-99b6-bda90efd3e10.png">

**Comment by chrissrogers** [comment]
If you see this again can you log the complete response from the endpoint?

**Comment by jchayan** [comment]
@chrissrogers Understood, from what I saw, the response came totally empty. But if it happens again I will try to get more information. Also, I simulated 1000 requests manually using cURL and didn't manage to reproduce it. And by submitting the form using recurlyjs, the issue happens very randomly, you get a 302, then when submitting again, you get 200..

**Comment by jchayan** [comment]
Reproduced again.

Clicked on subscribe and makes the ajax to /token, which responds with a 302, empty response
Then, another request was fired to "https://api.recurly.com/js/v1/field.html", responds with 200 with the following content:

```<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <meta name="viewport" content="width=device-width initial-scale=1.0"</meta>
    <style>
      html, body {
        margin: 0;
        padding: 0;
        height: 100%;
        width: 100%;
        background: transparent;
      }

      input {
        background: transparent;
        border: none;
        display: inline-block;
        width: 100%;
        height: 100%;
        margin: 0;
        outline: none;
        box-sizing: border-box;
      }
    </style>
  </head>
  <body>
    <input id="recurly-hosted-field-input" type="text"></input>
    <script>
      (function () {
        document.body.appendChild(tag());

        function tag () {
          var script = document.createElement('script');
          script.src = url();
          return script;
        }

        function url () {
          var current = parseURL(window.location);
          var host = current.host.replace('api.', 'js.');
          return current.protocol + '//' + host + '/hosted-field/v1/hosted-field.js'
        }

        function parseURL (url) {
          var parser = document.createElement('a');
          parser.href = url;
          return parser;
        };
      })();
    </script>
  </body>
</html>
```

**Comment by jchayan** [comment]
Here's the HAR files for both requests:

[requests.zip](https://github.com/recurly/recurly-js/files/772294/requests.zip)

**Comment by jchayan** [comment]
Is anyone else facing this issue?

**Comment by chrissrogers** [comment]
This is the only reported case that I am aware of

**Comment by johnnymalloy** [comment]
I have the same problem. I cannot seem to recreate it with consistency. I definitely get the 302 response. If I resubmit a second time it always seems to then go through just fine.

**Comment by chrissrogers** [comment]
Just a heads up that we've identified the underlying cause of this issue. I'll update here when it's been fixed.

Just a note that this only affects browsers which have had an active login session to app.recurly.com -- so your customer impact should be nil. Hope this is helpful!

**Comment by jchayan** [comment]
@chrissrogers Hi, any news on this?

**Comment by chrissrogers** [comment]
@jchayan Ah yep, when @karentobo closed this it was because the fix had been issued. Please notify us of any issues you encounter!

**Comment by jchayan** [comment]
@chrissrogers Thank you, it's just that I couldn't refer myself to the commit link. Is the minified release updated with this? (https://js.recurly.com/v4/recurly.js)

**Comment by chrissrogers** [comment]
Totally. The fix was with our backend API, so no client update necessary.

**Comment by jchayan** [comment]
@chrissrogers Understood, thanks!
