### ISSUE TITLE
Hosted fields change event should be compatible with HTML5 input change event

### ISSUE THREAD

**Issue by amirangorgazjan** [recurly/recurly-js#331]
The change events for hosted fields are firing on any blur, focus and keypress events. For our use case this means that we cannot adequately respond when the user has actually changed their form information versus when they just focused on the field.

Additionally, the change event is also incorrectly fired after the "ready" event, which means that the change event is fired on startup even when the user hasn't changed a thing. The events are found in `hosted-field.js` and `hosted-fields.js`.

**Comment by chrissrogers** [comment]
The `change` event in recurly.js is somewhat distinct from HTML form changes. It fires when the state of the fields change, such as focus state, and not only when the values of those fields change. This allows an integration to know when any number of things about the fields has occurred. For a solution that works right now, I recommend tracking field values within your change listener if you need to react specifically to value changes.
