### ISSUE TITLE
Creating signature in node.js

### ISSUE THREAD

**Issue by cghobbs** [recurly/recurly-js#34]
I'm trying to integrate recurly.js into my node.js application. I'm receiving the following error when I submit a form though:

"Your payment session has expired for security. Please refresh the page and try again."

You can see the code I've written here:

https://github.com/cghobbs/pacific-commuter/blob/recurly/libs/recurly.js

Any ideas on what I'm doing wrong?

My best guess is it has something to do with the timestamp but I can't figure out what.

**Comment by mr-dignitty** [comment]
My issue is similar and looking for direction... 
It happens onsubmit of the recurly form and yields this error:
[https://drive.google.com/file/d/0B7iS1eIaKd5STnMtVWZ6Ym95RVU/view?usp=sharing](url)

I searched for this specific error and can't seem to find insight about it.. I'm thinking about reconnecting my payment credentials.. 

Error verbatim:

> The following error were encountered: This form has expired. Please refresh and try again
