### ISSUE TITLE
Change placeholder text at runtime

### ISSUE THREAD

**Issue by railsstudent** [recurly/recurly-js#342]
Due to new UX requirement, our application needs to change the placeholder text of a recurly host field at runtime?

Is it possible. Thanks.

**Comment by chrissrogers** [comment]
Absolutely. Just call `recurly.configure` again with the updated placeholder text.

**Comment by railsstudent** [comment]
Does not seem to work with AngularJS

**Comment by railsstudent** [comment]
I update placeholder text in change event handler but change does not occur. 
recurly.on('change', (state) => {
  ... some logic
  recurlyConfig.style.month.placeholder.content = '';
  recurly.configure(recurlyConfig);
});
$scope.apply()

Please advise. thanks.

**Comment by chrissrogers** [comment]
Do you have a live demo of the behavior you can share?
