### ISSUE TITLE
Coupon impact on total price

### ISSUE THREAD

**Issue by vojtech-dobes** [recurly/recurly-js#343]
We would like to create following table:

|                  |           |
|:----------|------:|
| Product A | $100 |
| Discount 1 *(20%)* | -$20 |
| Discount 2 *(50%)* | - $40 |
| **Total** | **$40** |

But unfortunately when calling `pricing.coupon()` twice, in the final object there is only single field `now.discount` without any further distinction.

Can `recurly.Pricing()` expose such detailed information or if not, would it be possible to add support for such thing :) ?

**Comment by chrissrogers** [comment]
I'm going to log this to our internal feature request log. We've just expanded our coupon support as part of #399, and are looking to add multiple coupon application as a follow-on to that work.
