### ISSUE TITLE
Clicking away from a Recurly input removes any added classes

### ISSUE THREAD

**Issue by JoelJeffrey** [recurly/recurly-js#349]
gif: https://gfycat.com/PeriodicAstonishingHousefly

explanation: I validate each individual input based on the recurly.state object and add classes to the input wrapper div accordingly.  If I use tab to go to the next field it works fine and shows the red border if invalid because of the invalid class.  But if I click away from the input it removes my added classes, as shown in the gif by the border having no color.

**Comment by chrissrogers** [comment]
Do you have a live example of the behavior? I would assume that if you are listening to the change event and basing your class assignment on the validations states.. which should certainly be static. It may be that your class assignment isn't getting a complete state object?

**Comment by JoelJeffrey** [comment]
Sadly I do not have a live example, I am using it in our React project, i'll post the changeHandler function to show you where I'm assigning the classes based of the recurly.state object.

```changeHandler(state) {
    let fields = state.fields

    this.setState(fields)

    Object.keys(fields).forEach(function(key,index) {
      let $numList = window.$(`.recurly-hosted-field-${key}`);
      if (fields[key].empty) {
        $numList.removeClass('valid', 'invalid');
      } else if (fields[key].valid) {
        $numList.addClass('valid').removeClass('invalid');
      } else {
        $numList.addClass('invalid').removeClass('valid');
      }
    });
  }
```

Even when I console.log the state of each input it shows invalid (as i'd expect), it just removes classes on click away of that element.  i can show a gif of it with the console.log if that helps

**Comment by JoelJeffrey** [comment]
I was able to make a work around this issue by adding the valid/invalid classes to a wrapper around the recurly injected <div>, as it kept stripping the classes when clicked out of the recurly form.

**Comment by chrissrogers** [comment]
That seems so curious to me. Glad you found a workaround, but I do wonder which class removal command is firing on field blur, and what the state object is at that time.

**Comment by JoelJeffrey** [comment]
The state object remains invalid in my example, I console log all the state values on any change, and the field in the above example remains invalid.  I'm doing the same logic as above just to the <div data-recurly="number"></div> instead of the ".recurly-hosted-field" class and it works fine.

If there is anything specific you'd like to know about it I'll try testing it, but it seems the classes on <div class="recurly-hosted-field"></div> are getting reset when clicked outside of a recurly input/frame.  I noticed it happens even when I tab out of the cvv input because it leaves the recurly inputs.

**Comment by chrissrogers** [comment]
Oh yes of course, now I see your problem. Those divs reset their classes when the state changes, in order to remove the focus class, and they will remove any additional class added. Your solution is correct. I will close this for now. Cheers!
