### ISSUE TITLE
Object.assign not supported in IE

### ISSUE THREAD

**Issue by ericschmidtatwork** [recurly/recurly-js#350]
The built JS provided by the Recurly CDN uses `Object.assign`, which is not supported in Internet Explorer. Are we expected to include a polyfill?

This was discovered when trying to use the PayPal integration on IE 11.

**Comment by chrissrogers** [comment]
@ericschmidtatwork Thanks for pointing that out. This had been used in the ApplePay integration and incorrectly adapted into other modules.

Best to use a polyfill for now until the calls are removed. I'm also curious how the IE11 CI environment gets a polyfill..
