### ISSUE TITLE
PayPal callbacks not firing in IE 11

### ISSUE THREAD

**Issue by ericschmidtatwork** [recurly/recurly-js#351]
Using both the old PayPal integration and the new one, callbacks do not appear to be called in Internet Explorer 11. Examples (with jQuery and a button called `$submit`) are given below.

Example (old):
```js
$submit.on('click', () => {
  recurly.paypal(
    { description: '...' },
    (err, token) => {
      console.log(err, token);
    }
  );
});
```

Example (new):
```js
const paypal = recurly.PayPal({ ...opts });
paypal.on('error', err => {
  console.log(err);
});
paypal.on('token', token => {
  console.log(token);
});
$submit.on('click', () => { paypal.start(); });
```

In both cases, the external PayPal popup opens successfully. But regardless of whether I cancel the transaction or complete it, nothing is logged to the console and there appear to be no JavaScript errors.

**Comment by chrissrogers** [comment]
Thanks for reporting this. You can enable verbose debugging by setting `localStorage.debug = '*'` -- are there any helpful errors in those messages?

I'll also have a look at this soon to reproduce the issue.

**Comment by ericschmidtatwork** [comment]
Thanks for the quick reply! There are some innocuous-looking logs and then a message saying `opening frame window` when the popup opens, but nothing after that (again regardless of whether I cancel or complete the transaction).

**Comment by chrissrogers** [comment]
Just a heads up that I'm still working on this fix. It's related to the relay workaround we have to implement for IE's cross-domain cross-frame communication restrictions.

**Comment by chrissrogers** [comment]
Another update: we have a fix ready for the next release of our backend API. I don't have an exact release date, but stay tuned.

**Comment by simonweil** [comment]
Hi @chrissrogers,
We are suffering from the same issue,
Is there any ETA for the fix going live?

**Comment by chrissrogers** [comment]
Sorry for not updating this. The fix I identified went into production in mid-June. I was able to reproduce the bug and no longer see it occurring in production -- but it's certainly possible that there is another error occurring in IE11. @simonweil do you have repro steps?
