### ISSUE TITLE
Add company name field to the supported data-recurly fields

### ISSUE THREAD

**Issue by thgreasi** [recurly/recurly-js#357]
Can you add the company name to [posted fields](https://github.com/recurly/recurly-js/blob/611fbdeba93fe5d86057aa427963508f8188463d/lib/recurly/token.js#L17-L30)?
It seems logical since the respective Billing Info Hosted Page supports it.

**Comment by chrissrogers** [comment]
Funny you should mention that. I actually had those changes in my working copy. Should go in next version. #358

**Comment by thgreasi** [comment]
👍 crazy coincidence 👍 
When 4.6.2 is going to start on https://js.recurly.com/v4/recurly.js ??
In the mean time it would be great if there was a way to programmatically check whether the company (or any other) field is supported by the current version.
Thanks again!

**Comment by chrissrogers** [comment]
Programatically, you can check `recurly.version` for compatibility. We don't have a specific date, but when it does go live the release will indicate as much. Cheers!
