### ISSUE TITLE
Can't make the Paypal example work w/ sandbox account

### ISSUE THREAD

**Issue by thgreasi** [recurly/recurly-js#359]
I've been trying the provided [PayPal integration example](https://github.com/recurly/recurly-js-examples/blob/master/public/paypal/index.html) with my **Recurly account which is still in sandbox mode**, but get this error:
```js
{
    "code": "paypal-tokenize-error",
    "name": "paypal-tokenize-error",
    "message": "An error occurred while attempting to generate the PayPal token",
    "cause": {
        "code": "paypal-not-configured",
        "message": "Please configure a PayPal account with reference transactions in Recurly before accepting PayPal payments."
    }
}
```
Using the same public key, the credit card and bank account examples worked out of the box, it's just PayPa that troubles me.

I've created a **sandbox PayPal account** and used its token to configure a PayPal Payments Pro (UK) Gateway on Recurly. *Some docs on this would be great to have!*

A representative told me that I currently can't test PayPal on sandbox Recurly accounts but I thought that I should open a GH issue as well. Can you confirm this?

Thanks up front!

**Comment by chrissrogers** [comment]
I think you'll need to direct this toward our support team. They'll help you figure out your configuration issue.

**Comment by thgreasi** [comment]
Actually, I did talk with a support representative on 2017-06-22 and I was told that:
> Unfortunately, while in sandbox mode you will not be able to test PayPal. We do have a feature request for this that I have added you to and should it become available we will be in touch.

Can you confirm or reject the above?
Thanks.

**Comment by chrissrogers** [comment]
Yes I believe that is correct. However, these issues are more for code issues and proposals :)

**Comment by iBrazilian2** [comment]
Was this feature every implemented?

**Comment by chrissrogers** [comment]
@iBrazilian2 sorry for not seeing your question earlier! It is possible to use a PayPal sandbox account using reference transactions, but it must be a PayPal Business account, as opposed to a PayPal Payments Pro account. The PayPal features in Recurly.js are intended to provide reference transaction flows.

If you're using PayPal Payments Pro, then you can accept credit cards using the Recurly.js Elements (the new version of Hosted Fields) feature.

Hope that helps!
