### ISSUE TITLE
Validation of address

### ISSUE THREAD

**Issue by vojtech-dobes** [recurly/recurly-js#364]
Recurly clearly has built-in validation of address, because attempt to retrieve token with nonsensical address results in specific error. Is there some API how to use this validation prior to obtaining token itself?

**Comment by chrissrogers** [comment]
We don't have an endpoint specifically for validating addresses, sorry. When creating a token, we check that the address complies with basic rules about formatting, but extensive address checks against a customer's billing address do not typically occur until we create a transaction with your gateway.

**Comment by vojtech-dobes** [comment]
@chrissrogers Thanks for your answer.
