### ISSUE TITLE
Handling paypal in the same window

### ISSUE THREAD

**Issue by ecdeveloper** [recurly/recurly-js#366]
Using old paypal integration, currently when I initiate the paypal flow, it opens a new tab. Is there a way to proceed to PayPal within the same tab/window? Couldn't find anything useful in the docs in this regard. 

I'm using Recurly v3:

```javascript
let options = {
   description: 'some text here',
};

recurly.paypal(options, (err, token) => { ... }
```

Thanks in advance.

**Comment by chrissrogers** [comment]
It is not possible a this time, unfortunately. We chose to use a new tab/window in order to preserve the state of the merchant checkout page -- often it is difficult to restore the state of things on a checkout page after a redirect.
