### ISSUE TITLE
Autocomplete / Autofill does not work

### ISSUE THREAD

**Issue by tommoor** [recurly/recurly-js#368]
⚠️ **Warning** ⚠️  to folks thinking about using Recurly and this library for taking payments. The library prevents browsers autofill/autocomplete from working so your customers will need to type out their payment details manually.

Braintree previously had the [same issue](https://github.com/braintree/braintree-web/issues/216) with their hosted fields implementation.

**Comment by chrissrogers** [comment]
@tommoor we're definitely aware of the limitation of hosted fields in collecting credit card numbers from browser autofills, and are aware of the workaround Braintree introduced, which you reference. I can say that we have this feature in mind for an upcoming release, so stay tuned!

**Comment by mariane-bekker** [comment]
Hi @chrissrogers Can you please give an ETA on when the autofill capability will be released? This is a very important feature for us. Thanks

**Comment by chrissrogers** [comment]
I expect it to deploy to our CDN this Thursday. I'll let you know if it delays at all, but it should go out then.

**Comment by tommoor** [comment]
It *looks* like this was fixed - confirm @chrissrogers ? If so, thanks!

**Comment by chrissrogers** [comment]
Yes I can confirm that this has been added as of yesterday. Cheers!
