### ISSUE TITLE
Apple Pay init error - "" is not a valid amount

### ISSUE THREAD

**Issue by jonaslundquist** [recurly/recurly-js#371]
Following [this example](https://docs.recurly.com/v1.0/docs/apple-pay-on-the-web), when running `applePay.begin`, an exception is thrown with the message `Error: "" is not a valid amount.`.

I think the issue is that in apple-pay.js lines 153 through 155, the initialization only attaches handlers for pricing changes but never actually update `this.config.total` which means that if prices aren't changed in the time window between Apple Pay setup and `applePay.begin` is called from client, `this.config.total` in line apple-pay.js:86 won't be set, presumably causing the error.

In our environment Apple Pay has to be initialized at a later stage than rest of Recurly, so it could be that `onPricingChange` is never called for Apple Pay if the user chooses not to change it.

Until this is fixed, is there a clean way to force reload the pricing module without actually changing the pricing?

**Comment by chrissrogers** [comment]
Okay, yes it makes sense that the initialization order would cause this.

I think a change is in order for the total to be updated during initialization. In the meantime, you can either call `applePay.onPricingChange` directly, or call `pricing.emit('change')` in order to induce the event.

**Comment by jonaslundquist** [comment]
Great, thanks!
