### ISSUE TITLE
Documentation: (1) Full list of recurly.configure options and (2) calling recurly.token with an object rather than form element

### ISSUE THREAD

**Issue by rognstad** [recurly/recurly-js#373]
Hi,

I noticed a couple of minor documentation issues for Recurly.js:

1. In the "Styling Card Fields" section (https://dev.recurly.com/docs/getting-started-1#section-styling-card-fields) under the "Fonts" heading, the text indicates that there should be a complete list of options "to the right" to use when calling recurly.configure. There isn't anything to the right. There is a rather large example in the main column a bit above that text, but it's not clear if that is a complete example. It seems like it probably isn't since #241 talks about font smoothing, which isn't in the example. It would be very nice to have a truly complete list of available options.

2. The section on the recurly.token API (https://dev.recurly.com/docs/getting-a-token#section-recurly-token-api-) has conflicting information. It opens by saying that one must pass a form element as the first argument. After the JS sample, though, the following text exists:

> There are two ways to call recurly.token: with a form, and with an object.
> 
> The simplest is to pass it a form element containing form fields with their corresponding data-recurly attributes.

Thanks,
Matt

**Comment by chrissrogers** [comment]
@rognstad thanks! I've updated the docs with your suggestions. Thank you so much for the keen eye!

Are you working on an integration at the moment? Any suggestions or feedback you can give, we would be glad to receive.

**Comment by rognstad** [comment]
Wow, that was really fast! It looks like fontSmoothing isn't in the styling example, though, and #241 makes me think it should be there. Also, are there any other options that are missing (I suppose I could just look at the code)?

I'm updating an old v3 integration I inherited to v4.

I'm a little disappointed to have to get rid of select elements for month and year, but I found the issue requesting that and can understand not supporting it.

Another nicety I'm losing as part of the update is the ability to show a card logo based on the number entered. When I look at your iframe, I can see a class added to the input element. Perhaps you could bubble that like the existing recurly-hosted-field-focus class. I don't know that adding the card logo is a huge usability win, but I think it might slightly decrease the chance of typos/help users know when they've entered the correct number of digits (though admittedly the automatic formatting of the number helps with this already).I'm happy to submit a separate issue to request this. 

Finally, this is my first time working with Recurly, and I incorrectly believed recurly.token would/should return an error when using an invalid CC number (e.g. your test numbers: https://docs.recurly.com/docs/test#section-test-credit-card-numbers). I spent a little time chasing my tail wondering why I was getting a token for an invalid card (even when using your example forms). In hindsight, it makes sense that an error like insufficient funds couldn't be returned without knowing the amount to be charged and another API call was necessary, but I was mainly looking at AVS stuff. It might be worth adding a small note that recurly.token merely validates the well-formedness of the CC info.

**Comment by chrissrogers** [comment]
Awesome, that's really wonderful feedback. Thanks for sharing it. I updated the docs to include font smoothing. you're right that there are undocumented configuration options, some of which we're releasing slowly, so documentation will come. Be assured that if it's in master, it's stable.

As for select inputs for month and year, we are looking at ways to support them on mobile only, as it's their most appropriate use-case.

> Another nicety I'm losing as part of the update is the ability to show a card logo based on the number entered.

It should be possible to do this by listening to the `'change'` event, and updating a card icon based on the `state.fields.number.brand` value. I think it's a useful bit of feedback UX, certainly. And please stay tuned for hosted field updates that could make such a thing easier to implement.

That's a great suggestion to explain the validation limitations of the tokenization process. I think I'll take some time to review and add a few notes saying as much. Cheers!

**Comment by rognstad** [comment]
Thanks for pointing me to the recurly change event! I don't know how I missed that in the docs. That will be tremendously useful.
