### ISSUE TITLE
Error styling

### ISSUE THREAD

**Issue by DannyJoris** [recurly/recurly-js#376]
I'm looking for a way to style Recurly input fields on error. I can add a class on the wrapper to style the border, but I'd like to change the text color as well. Is this possible?

**Comment by chrissrogers** [comment]
Hi @DannyJoris yes you sure can. The best way to do this is to make a `recurly.configure` call when there is an error present, and update the fontColor of the field on which there is an error. For the best UX, you can also listen to the `change` event and clear the error highlight when the field is detected to be valid. That state value will update as your customer types into the field.

Cheers! Hope that's helpful.

**Comment by DannyJoris** [comment]
This is not working for me. Something like this, but instead of `all` the specific field? At this point I've already called `recurly.configure` to set the default styling.
```
        recurly.on('change', state => {
            recurly.configure({
                publicKey: recurly_key,
                fields: {
                    all: {
                        style: {
                            fontColor: '#ce1d00',
                            placeholder: {
                                color: '#ce1d00 !important',
                            },
                        },
                    },
                },
            });
        });
```

**Comment by chrissrogers** [comment]
Yes, that's essentially correct. You won't need to include the publicKey on your follow-up calls.

But while investigating this, I've uncovered a regression that had been introduced, which affects this behavior directly. I've patched the issue, and will notify you here when it's been released to our CDN.
