### ISSUE TITLE
Bus is undefined when configuring with parent = false

### ISSUE THREAD

**Issue by boyasonglucid** [recurly/recurly-js#397]
We've been configuring recurly with parent set to false and we did not inject form fields through recurly. This worked fine with version v4.1.0, however when we updated to v4.7.1 PayPal broke. This was because PayPal now uses Frame which needs a Bus. Bus is not initialized unless parent is set to true during configuration. Since we are not injecting form fields using recurly, changing the parent setting broke regular credit card payments.
Is this a bug or is recurly no longer supporting not injecting form fields?

**Comment by chrissrogers** [comment]
@boyasonglucid `parent` is intended to be an internal-only configuration value, and shouldn't be set. Unfortunately, we can't support any configuration that circumvents hosted fields, as our intention is to help comply with the lowest level PCI DSS SAQ-A. So I absolutely recommend updating your configuration to use hosted fields.
