### ISSUE TITLE
Checkout with PayPal in private window mode

### ISSUE THREAD

**Issue by Kroshtandt** [recurly/recurly-js#419]
Hello everyone! 

I'm using recurly.js 4.0 in my project for checkout process. All is good with the card payments and with PayPal payment in regular window (Google Chrome - Version 63.0.3239.132 (Official Build) (64-bit)).
The issue is when I open my website in the **private window** in any browser on the Chrome engine the event:

` paypal.on('token', function (token) { /*my code is here*/ });`
does not invoke my code inside after successful payment and automatic paypal window closing. 
My checkout still showing loading notification screen.. 

This only happens only in **private window** with the Chrome engine browsers.

Full code:
```
var paypal = recurly.PayPal({
        display: { displayName: 'name' }
});
if (paypal) {
        paypal.start();

        paypal.on('token', function (token) { /*my code is here*/ });

        paypal.on('error', function (err) { /*errors handle code*/ });
        paypal.on('cancel', function (event) { /*cancel handle code*/ });
}
```

Also I can not check 
`
paypal.on('cancel', function (event) { });
`
This function does not call also. I think this should invoke when user close window or click cancel inside paypal window? This also is not working for me, I have no idea how to test it.

Any ideas?

**Comment by chrissrogers** [comment]
This is an interesting scenario. We don't specifically test incognito or private browser sessions. I suspect that Chrome sandboxing is preventing communication between the windows, which is necessary to relay the customer data back to the Recurly.js instance on your checkout page.

To debug this further, do you encounter any errors in the chrome console from the paypal checkout window?

**Comment by Kroshtandt** [comment]
@chrissrogers  Nothing in console, no errors or warnings. 
But I have noticed that unsecured connection (http://) in any Safari browsers doesn't allow window opening (like in our case with paypal window), so we can not test it properly. Also we have noticed that all works fine with https:// connection.

The next issues is:
1. Chrome incognito window does not opening paypal window
2. Unsecured connections in Safari browser also doesn't allow to open paypal window

All the best!

**Comment by chrissrogers** [comment]
I recommend always transmitting your payment pages over SSL :)

**Comment by chrissrogers** [comment]
Testing indicates that communication between the windows will not be possible, thus the PayPal window will be unable to indicate to the original window when the transaction has succeeded. At this time this doesn't seem possible, unfortunately 😞Closing this for now.
