### ISSUE TITLE
Firefox focus field issue

### ISSUE THREAD

**Issue by hubentom** [recurly/recurly-js#422]
the action is to go to (for example) Card Number recurly js field and put cursor in the field. Then put the cursor into the next field or another field removing focus - this should remove the classes containing the word FOCUS from the card number div. This doesn't happen in Firefox.

<div data-recurly="number">
      <div class="recurly-hosted-field recurly-hosted-field-number **recurly-hosted-field-focus recurly-hosted-field-number-focus**">
        <iframe src=....

**Comment by chrissrogers** [comment]
Thanks for reporting. We'll have a look at this to see what the cause may be. Would you describe it mostly as a problem of the blur event not registering in Firefox? If you have a demo for this, that would be greatly appreciated too.

**Comment by hubentom** [comment]
i have a private demo / url explaining both issues - can you email me dev@hypeddit.com

**Comment by hubentom** [comment]
Hi Chris - let me know if you can email me dev@hypeddit.com or i can email you

**Comment by chrissrogers** [comment]
I've just sent an email and look forward to helping out with this
