### ISSUE TITLE
Firefox credit card fields in a modal

### ISSUE THREAD

**Issue by hubentom** [recurly/recurly-js#423]
In firefox, a simple bootstrap modal is not tabbing correctly - works fine in Chrome... put  recurly.js fields (card number, month, year) and then a couple other fields like first name last name after these into a modal. launch the modal, in firefox the modal tabbing does not work properly - will tab between recurly js fields and fields before this but not the other fields.

**Comment by chrissrogers** [comment]
Thanks for the report @hubentom -- do you have a demonstration to illustrate this? It will go far to diagnosing the structural situation here. Tabbing on desktop browsers is typically able to map through iframes without any issues. This may be due to the placement of the modal in the DOM.

**Comment by chrissrogers** [comment]
So the behavior I see in firefox in the demo is that tabbing forward works normally, but when tabbing to previous fields, it will focus on the iframe window before moving to the previous field. Does that match the behavior you're seeing? I tested with Firefox 57 and 58.
