### ISSUE TITLE
Firefox: Red border around hosted fields

### ISSUE THREAD

**Issue by ellotheth** [recurly/recurly-js#427]
In Firefox using the `card` iframe, the _Date_ field gains a red border on blur:

![image](https://user-images.githubusercontent.com/977114/36252164-f1fc2c82-1243-11e8-8cec-44251e7e3c21.png)

The border is coming from Firefox's default `box-shadow` CSS style on `input` fields that don't meet their validation constraints:

> By default, Gecko applies a style that creates a red "glow" (using the box-shadow property) around items, which have this pseudo-class applied.

[(source)](https://developer.mozilla.org/en-US/docs/Web/CSS/%3A-moz-ui-invalid)

As far as I can tell, the `box-shadow` property is not available in the `recurly.configure()` options. I tried `boxShadow: 'none'` and `boxShadow: 'unset'`.

I'd like a way to remove the red border (exposing `box-shadow` in the `recurly.configure()` options, or adding it to the hosted CSS, or changing the validation constraints on the field, or whatever).

**Comment by chrissrogers** [comment]
Good catch! I'll have something to address this shortly

**Comment by chrissrogers** [comment]
Just an update: we've found the appropriate fix and will need to implement it on our hosted frame component. I don't have a specific timeline, but when the fix deploys, it will not require any configuration changes on your part -- the red border will simply not appear in Firefox any more.

**Comment by ellotheth** [comment]
Spectacular, thank you!

**Comment by chrissrogers** [comment]
@ellotheth this went out in a new version yesterday. Thanks again for the report!
