### ISSUE TITLE
Using recurly.token with billing info object instead of form selector

### ISSUE THREAD

**Issue by docmattman** [recurly/recurly-js#434]
I'm getting an error when attempting to call `recurly.token(object, callback)` using an object instead of a query selector:

```
var billingInfo = {
    // required attributes
    number: '4111-1111-1111-1111',
    month: '08',
    year: '2025',
    cvv: '123',

    first_name: 'Pat',
    last_name: 'Smith',

    // optional attributes
    address1: '123 Main St.',
    address2: 'Unit 1',
    city: 'Hope',
    state: 'WA',
    postal_code: '98552',
    country: 'US',
};

recurly.token(billingInfo, function(err, token) {
    if (err) {
        console.log('recurly error', err);
    } else {
        console.log('recurly success', token);
    }
});
```

The above code throws an error: 

```
code: "missing-hosted-field-target"
message: "Target element not found for number field using selector '[data-recurly=number]'"
name: "missing-hosted-field-target"
selector: "[data-recurly=number]"
type: "number"
```

Is there a way to accomplish this without errors?  The docs say that a query selector must be used as the first parameter, however, the source code shows this (from the `recurly-js/lib/recurly/token.js` file):

```
/**
 * Generates a token from customer data.
 *
 * The callback signature: `err, response` where `err` is a
 * connection, request, or server error, and `response` is the
 * recurly service response. The generated token is accessed
 * at `response.token`.
 *
 * @param {Object|HTMLFormElement} options Billing properties or an HTMLFormElement
 * with children corresponding to billing properties via 'data-reurly' attributes.
 * @param {String} options.first_name customer first name
 * @param {String} options.last_name customer last name
 * @param {String} [options.address1]
 * @param {String} [options.address2]
 * @param {String} [options.country]
 * @param {String} [options.city]
 * @param {String} [options.state]
 * @param {String|Number} [options.postal_code]
 * @param {Function} done callback
 */
```

This states that the first parameter may be an object or a form element.  In my case, I'd like to pass in an object, since I cannot easily modify my form to include the `data-recurly` attributes.

**Comment by chrissrogers** [comment]
@docmattman -- great questions! So the `recurly.token` method can accept an object to initiate tokenization, but it is limited to customer billing info up to the actual card data. Ultimately, recurly.js must obtain the credit card information from hosted fields for the `number`, `month`, `year`, and `cvv`. This is due to PCI restrictions on access to that customer data.

Those hosted fields are built following a `recurly.configure` call, and by default will look for a target using the selector `[data-recurly=FIELD_TYPE]`. The best outline for setting up a form for those default selectors can be found here: https://dev.recurly.com/docs/recurly-js-getting-started#section-build-a-card-form

Hope this answers your questions!

**Comment by docmattman** [comment]
@chrissrogers, thanks for clearing that up.

Let's say that I'm unable to modify the form HTML and add in the `data-recurly' parameters (I'm using a form generator from a defined schema that doesn't have the ability to add custom data attributes).  Is there a way I can configure it to define the input fields to use without the `data-recurly` attributes?  For example, could I map the card `number` field (and the other fields) to an input element manually instead of it just looking for the `data-recurly="number"` attributes automatically?

What I was trying to accomplish in my original post was using JS to get the values from my form and just plug them into the `recurly.token` method using an object (since I was unable to add the custom attributes).

Do you know of a way to accomplish this?

**Comment by chrissrogers** [comment]
You can specify custom selectors, but you won't be able to point to plain input fields for the card data, they'll need to be container elements like a `<div>` in which the hosted fields can be injected. This restriction stems from the requirement that card data be hosted entirely by Recurly, and thus cannot be directly accessed on your checkout page by other scripts.

```js
recurly.configure({
  // ...
  fields: {
    number: {
      selector: 'custom-selector'
    },
    // ...
  }
  // ...
});
```

**Comment by docmattman** [comment]
Ok, thanks for the info.  I'll explore the options and see what I can come up with.

**Comment by chrissrogers** [comment]
Sounds great! I'll close this, but feel free to open anything else
