### ISSUE TITLE
Documentation is inconsistent about multiple calls to recurly.configure.

### ISSUE THREAD

**Issue by kalokiston** [recurly/recurly-js#436]
Under the "Error Codes" section of the [documentation for recurly.js errors](https://dev.recurly.com/docs/recurly-js-errors), there is an entry for the code `already-configured` with description:

> A recurly instance may only be configured once. Doing so more than once is excessive.

However in the ["Responsive Styles" section](https://dev.recurly.com/docs/recurly-js-getting-started#section-responsive-styles) it says:

> You may call recurly.configure again to change style properties.

Furthermore in #267, @chrissrogers says  

> the internals allow for you to call the recurly.configure method many times with different targets 

Please clarify what is going on with recurly.configure. A clear semantics is needed for this confusing situation. On the one hand most people would assume that configuring a singleton should happen only once so the error code makes sense. But then it says it can be called multiple times to change style. Then it says it can be called multiple times to create an entirely new target. 

This is all very confusing.

**Comment by chrissrogers** [comment]
Agreed! Thanks for pointing this out. I have updated the documentation to remove the error code description. This error code was deprecated at v4.3.0 to coincide with the feature in #267, and is no longer thrown.

It is possible to call `recurly.convfigure` multiple times to update the configuration settings on the singleton. Changes are propagated to the hosted fields, and in the case of a different field target selector, the fields will re-locate and reinitialize. Apologies for the confusion in our documentation. Hopefully I've helped clarify some!

**Comment by kalokiston** [comment]
Thanks, that does clarify some things. A few follow ups though:

1. Is it safe to call `recurly.configure()` with a new target while a `recurly.token()` call is running? 
2. Same as above but with `recurly.configure()` won't change the target.
2. Once a `recurly.configure()` call is make with a new target, is it possible to call `recurly.token()` on the old target?

**Comment by chrissrogers** [comment]
Great! I'll do my best to answer.
1. I recommend waiting until the token call is finished. Since token responses are relayed through hosted fields, destroying one will result in the response not being relayed back.
2. This should be no problem, since the original hosted field remains in tact and can still act as a relay.
3. You won't be able to call `recurly.token` on the old targets unfortunately. The hosted fields will re-instantiate in the new position, and the token call will need to gather card data from that new position.

**Comment by kalokiston** [comment]
Thanks for the clarification.

IMHO it seems like it was a mistake to make recurly a singleton. It would have been a simpler API to instantiate a separate recurly object for each form and have it tied to that form. There would be no issue with trampling responses, we would access to the token() call for each recurly instance concurrently, and would generally be more intuitive than having to call configure().

But this does what I need I suppose.

**Comment by chrissrogers** [comment]
Thank you for the feedback, and I do agree that there are myriad benefits to moving away from the singleton pattern, especially as Recurly.js has become more complex over the years. Rest assured that there are plans in the works for doing exactly that.

**Comment by kalokiston** [comment]
Either way though, `recurly.configure`, especially with new target, needs to be documented on the official documentation page. 

The documentation pretty much assumes that there is a static form and recurly can be configured to work with that form. This is a very different model than a lot of applications. I almost gave up on Recurly because of this until I got lucky and stumbled on #267. #267 was 2 years ago, it should really have made it to the docs by now. It reflects poorly that it has not.
