### ISSUE TITLE
Is CVV, address, zipcode, etc checked against the card during tokenization, or when using the token to add billing info, or on actual billing?

### ISSUE THREAD

**Issue by kalokiston** [recurly/recurly-js#437]
Can I get some clarification on when the card information is checked? Does it happen:

1. When the token is generated?
2. When using the token to say add a billing info to an account?
3. On actual billing?

**Comment by chrissrogers** [comment]
Card billing details are not verified agains the card account holder until a card authorization or transaction occurs. This occurs in scenarios 2 and 3. Hope this helps :)

**Comment by kalokiston** [comment]
So an authorization happens when the billing info is added to an account?

**Comment by chrissrogers** [comment]
Yep, that's correct
