### ISSUE TITLE
Fix spacing of expiry and CVV in the Card field.

### ISSUE THREAD

**Issue by kalokiston** [recurly/recurly-js#438]
I'm having problems with the spacing in the card hosted field, in particular the expiry and CVV inputs. They seem to overlay each other. The 'Y' in YY is cut off:

<img width="614" alt="screen shot 2018-03-15 at 3 24 28 pm" src="https://user-images.githubusercontent.com/37417106/37494213-1c9307e0-2865-11e8-9829-e9d2694edf6d.png">

It is not due to the lack of space, which would be understandable. As you can see there is plenty of space available between the end of the card number and the beginning of the expiry that is not being used.

It gets worse when it is populated. Now the numbers are cut off. 

<img width="612" alt="screen shot 2018-03-15 at 3 25 05 pm" src="https://user-images.githubusercontent.com/37417106/37494231-2ae87690-2865-11e8-9bb2-d6f717844909.png">

For reference I am using Montserrat for fontFamily and fontSize is 20px.

Is there a way to fix this? 

I can solve this by making the font size much smaller, but there there is even more wasted space between the number and the expiry, and overall just looks bad. I would like a solution that keeps the font size roughly the same.

**Comment by chrissrogers** [comment]
For now the best solution will have to be reducing the font size, or using separate fields for the number, expiry, and cvv. The proportions on the card hosted field are currently locked, and the layout is designed to be a bit proscriptive. Ultimately, the best way to get a fully custom appearance would be to use separate fields for the card number, expiry, and cvv.

fyi, I've logged a request to support larger font sizes, or to influence the proportions of number, expiry, and cvv.

**Comment by kalokiston** [comment]
Ok, thanks.
