### ISSUE TITLE
FireFox: Credit card form doesn't initialize properly when hidden at time of initialization

### ISSUE THREAD

**Issue by irphilli** [recurly/recurly-js#440]
Steps to reproduce:
* Have div with credit card fields within it hidden
* call recurly.configure()
* Show div

The credit card field isn't properly initialized.  Only happens with FireFox.

**Comment by chrissrogers** [comment]
@irphilli thanks for the report. Do you see any console errors? Which version of Firefox are you using?

**Comment by irphilli** [comment]
No console errors.

FF 59.0.1 on Mac OS.  Though, I have team members who have also been experiencing it on the Windows version.

**Comment by chrissrogers** [comment]
Thanks for that. Hopefully there is something we can do to address it, but it may ultimately be a browser behavioral thing with iframe injection. To get around it for now you may wish to configure rjs once the fields are visible.

**Comment by irphilli** [comment]
Yeah, work around is to just reconfigure.

Also, I was mistaken about the JS error - this one popped up:
TypeError: e.document.defaultView.getComputedStyle(...) is null

**Comment by chrissrogers** [comment]
Ah great, that's very helpful. Is there a stacktrace available for that error, and does it occur at the moment of page init or some other interaction?

`getComputedStyle` returns null if the page is loaded in an iframe with `display: none;`. The call is made in one of our dependencies (https://github.com/davidtheclark/tabbable), so it may be possible to just add some safety to that call.

**Comment by irphilli** [comment]
Looks like at init.

Here's the trace:

> TypeError: e.document.defaultView.getComputedStyle(...) is null[Learn More] hosted-field.js:4:4499
	t https://js.recurly.com/hosted-field/v1/hosted-field.js:4:4499
	t self-hosted:989:17
	n https://js.recurly.com/hosted-field/v1/hosted-field.js:1:12581
	t https://js.recurly.com/hosted-field/v1/hosted-field.js:1:30745
	n https://js.recurly.com/hosted-field/v1/hosted-field.js:4:899
	r https://js.recurly.com/hosted-field/v1/hosted-field.js:4:11168
	i https://js.recurly.com/hosted-field/v1/hosted-field.js:4:17851
	recurlyHostedField< https://js.recurly.com/hosted-field/v1/hosted-field.js:1:340
	t https://js.recurly.com/hosted-field/v1/hosted-field.js:1:124
	recurlyHostedField< https://js.recurly.com/hosted-field/v1/hosted-field.js:1:223
	<anonymous> https://js.recurly.com/hosted-field/v1/hosted-field.js:1:24

**Comment by chrissrogers** [comment]
Beautiful, thanks for that

**Comment by KingMob** [comment]
Any word on this? We're seeing the exact same bug in FF. In our case, we have a bunch of tabs in our page, and the Recurly tab isn't displayed at the time of configuration.

**Comment by chrissrogers** [comment]
Unfortunately we don't have a fix prepared at this time, but we are working on it behind the scenes.

**Comment by chrissrogers** [comment]
Just noting that this was closed due to a fix being applied to our hosted field library. I don't have an exact deploy date yet, but when I do I'll update here.

**Comment by KingMob** [comment]
@chrissrogers Do you have a rough estimate of when that'll be? Like, next couple days, this week, sometime this month, etc...?

**Comment by chrissrogers** [comment]
Should be by the end of next week
