### ISSUE TITLE
Incorrect validation of card number

### ISSUE THREAD

**Issue by kalokiston** [recurly/recurly-js#441]
The `change` event reports the following for `event.fields.number` when the "number" hosted field is set to `4147 3002 3838`:

```
{
    "valid": true,
    "firstSix": "414730",
    "lastFour": "3838",
    "brand": "visa",
    "empty": false,
    "length": 13,
    "focus": true
}
```

Why is:
1. valid set to true?
2. length set to 13 instead of 12?

**Comment by chrissrogers** [comment]
The validation routine uses the luhn algorithm to check that a number may be valid. So technically the value may be a valid credit card number, even if no such card has been issued :)

The length value is the total length of the field input, incorporating the spaces into the total, which may not be desirable. We'll consider updating this to not include the spaces.. as for the length of 13, I actually see 14 when I test your value. Are you reliably getting 13?

**Comment by kalokiston** [comment]
I feel like once the brand is identified the validation should include the length as well. The `4` at the beginning identifies the number as being Visa and there are no 12 digit visa cards. So  `4147 3002 3838` should be trivially invalid.

It does not make any sense to me why length was chosen to include the spaces.

I actually get two consecutive events after I type in the last `8`. One with length 13 and the other with length 14.
```
{"valid":true,"firstSix":"414730","lastFour":"3838","brand":"visa","empty":false,"length":13,"focus":true}
{"valid":true,"firstSix":"414730","lastFour":"3838","brand":"visa","empty":false,"length":14,"focus":true}
```

**Comment by chrissrogers** [comment]
Thanks for the feedback on validations. We'll certainly consider making a change to expand beyond the luhn and broad card length checks, to something that validates more strictly based on card network.

**Comment by kalokiston** [comment]
Is it possible to get that in soon. It should be a trivial change. In fact I think just replacing `cardNumer` in `validate.js` with the following should do it:

```
export function cardNumber (number) {
  const str = parseCard(number);
  let ca, sum = 0, mul = 1;
  let i = str.length;

  if (i < 12 || i > 19) return false;

  while (i--) {
    ca = parseInt(str.charAt(i), 10) * mul;
    sum += ca - (ca > 9) * 9;
    mul ^= 3;
  }

  const luhnOk = sum % 10 === 0 && sum > 0;


  const currCardType = cardType(number, true)
  const currLen = str.length
  const card = find(TYPES, card => card.type === currCardType)
  const lenOk = card?
                card.lengths.some((len) => len === currLen):
                true
  return luhnOk && lenOk
}
```

**Comment by chrissrogers** [comment]
We made an update to our hosted library today that changed the length calculation to exclude separators, so the length value will now reflect the number of digits only. Cheers!

As for the request to enhance our card validation, we're still considering this and will update accordingly. I'm going to close this for now and keep the card validation piece as a request pending research.
