### ISSUE TITLE
Failed to decode downloaded font

### ISSUE THREAD

**Issue by kalokiston** [recurly/recurly-js#442]
I'm using the "Montserrat" font from Google Web Fonts. 

Every now and then I get the following error:

`Failed to decode downloaded font: https://fonts.gstatic.com/stats/Montserrat/normal/400`

It does not happen all the time and I am not sure what triggers it.

Incidentally, is there a way to provide the thickness of the font? The rest of my webpage uses 100 for the thickness, so the default 400 used in the hosted fields stands out.

**Comment by chrissrogers** [comment]
It's only possible to load the default weights at this time, but I've logged a request to add support for other weights. I don't have an exact timeline, but can assure that it will be implemented :)

I'm uncertain of the nature of the decode error, and we haven't encountered that before specifically. What is the fontFamily attribute value you are using?

**Comment by kalokiston** [comment]
`'fontFamily': 'Montserrat'`

**Comment by chrissrogers** [comment]
I'm closing this in favor of https://github.com/recurly/recurly-js/issues/360 :)
