### ISSUE TITLE
Recurlyjs v4 migration - invalid-public-key

### ISSUE THREAD

**Issue by jonathanstiansen** [recurly/recurly-js#444]
Recently migrated from Recurlyv2 to v4. When I try to submit the form I designed (the new v4 way) I get this error:

```
name: "api-error", code: "invalid-public-key", message: "Public key not found"
```

From v2 to v4, I've changed how `Recurly` is called. I call `recurly.configure('public-key-xxxx')`, after HTML is rendered and it seems to be working correctly, as when I call `recurly.config` in the console of the website I get this as an object:

```
api: "https://api.recurly.com/js/v1"
cors: true
currency: "USD"
fields: {all: {style: {}}, number: {selector: "[data-recurly=number]", style: {}}, month: {selector: "[data-recurly=month]", style: {}}, year: {selector: "[data-recurly=year]", style: {}}, cvv: {selector: "[data-recurly=cvv]", style: {}}, …}
fraud: {kount: {dataCollector: false}, litle: {sessionId: undefined}, braintree: {deviceData: undefined}}
parent: true
parentVersion: "4.8.3"
publicKey: "<redacted>"
required: [] (0)
timeout: 60000
```

I've read to be careful that this is `configure` is called after the html is rendered which I can confirm it is. 

Does anything explain why this key isn't working? It's the same key I used previously for V2, but I believe that shouldn't effect anything... right? 
Let me know what other info I can provide.

**Comment by chrissrogers** [comment]
The keys used changed between v2 and v3 -- you can find the new public key here on the right-hand side of the page: app.recurly.com/go/integrations/api_keys

Hope that helps!

**Comment by jonathanstiansen** [comment]
👍 thanks!

**Comment by chrissrogers** [comment]
@jonathanstiansen I'm not able to assist with that directly from here, but if you shoot our support folks an email at support@recurly.com they will be happy to help out!
