### ISSUE TITLE
Wrong SRI hash being specified in release notes for 4.8.5

### ISSUE THREAD

**Issue by davidgeary** [recurly/recurly-js#449]
According to the [release notes](https://github.com/recurly/recurly-js/releases/tag/v4.8.5) for 4.8.5, the SRI hash is `kB+7bDTPFuQgrKvspnHeYSDk0JpLU6sg4F85m6M6zDcKR4qYzMZLG1PVVcgDslla`, which surprisingly is the same as the hash for 4.8.4.

Using this hash results in browser errors, so I've checked the hash for the latest release on the CDN and it now appears to be `Y/AlQFZBGJll1dGRdJWRD4fSxYXPXOtJul9+RMwpLwphoDP3OPHEru6/UXMHasDH`.

Can anyone confirm this (and if so, update the release notes)?

**Comment by chrissrogers** [comment]
Thanks for pointing that out! I've verified the SRI hash and updated the release notes.
