### ISSUE TITLE
How do we avoid script references with the SRI hash breaking with every new release?

### ISSUE THREAD

**Issue by davidgeary** [recurly/recurly-js#450]
The deployment of the latest release of Recurly.js to the CDN has raised an interesting problem with regard to the use of the SRI hash.  Obviously the hash of the new version has changed, which is causing our page to fail to load it.  But even with Github or [Sibbell](https://about.sibbell.com/) notifications about new releases, we may not have time to update our page with the new hash before the release is deployed to the CDN.  And if we do, we then also need to time the deployment of our updated page to _exactly_ match that of the new release being deployed to the CDN, if we are to avoid our page being out of sync with the version on the CDN.

The best solution seems to be to have a way to specify the exact version of Recurly.js that the page is trying to load, but AFAIK, there's no way to do that as there's only one version of Recurly.js available on the CDN at any time.

Would it be possible to introduce a way to reference a specific version on the CDN?

If not, what is the recommended procedure for managing references to Recurly.js with the SRI hash so that we avoid our page breaking at every new release?

**Comment by chrissrogers** [comment]
We don't have any plans at the moment to make old versions available via our CDN, so I'm thinking the only way around it would be to download a copy of the library and keep it updated as frequently as possible, based on your current notification patterns. That will prevent the breakage delay you're experiencing, but it isn't something we encourage.

We've considered distributing past versions via CDN, but do want to avoid folks being locked into old versions as much as possible. But use-cases such as yours are one reason to do it.

**Comment by davidgeary** [comment]
Shame - pretty much makes the use of the SRI hash impractical for us in a production environment.
