### ISSUE TITLE
TypeError: Cannot read property 'tokenize' of undefined when calling start before PayPal is ready

### ISSUE THREAD

**Issue by thillmann** [recurly/recurly-js#457]
We're using Recurly.js in our Angular app and ran into an issue with the (Braintree) PayPal integration. 

In our checkout, when the user hits the payment button, we're creating a new PayPal instance (using `recurly.PayPal(...)`), setting up the necessary event listeners (for 'token', 'error' and 'cancel') and starting the paypal flow (`paypal.start()`).

However, we've ran into the following error doing so:

```javascript
Uncaught (in promise): TypeError: Cannot read property 'tokenize' of
undefined
TypeError: Cannot read property 'tokenize' of undefined
  at n.value (recurly.js:1)
  at t.value (recurly.js:1)
```

After debugging a bit, I've discovered that you have to manually ensure that PayPal has been loaded and is ready to use before calling `paypal.start()`. Otherwise the error above will be thrown. Unfortunately, the docs do not mention this.

I'd suggest to either defer the start call after it is ready (which could result in issues with the popup blocker in Chrome I think) or at least rejecting to start when calling it too early. Also I'd add this to the docs.

**Comment by chrissrogers** [comment]
@thillmann thanks for the report! Correct that the `start` call must be in a synchronous call from a user event.

Is it possible in your setup to initialize the paypal instance earlier? That may be the best order of operations. If you're awaiting the final price, then you may wish to instantiate each time the price is updated, or at a phase when you are confident the price is final.

There is a 'ready' event that is emitted when the paypal instance has finished initializing. You may wish to block the button click until that event has fired, which should eliminate the occurrence of that error.

Hope this is all helpful. Glad to help debug, and I think some documentation updates are in order

**Comment by thillmann** [comment]
@chrissrogers Yeah we're now waiting for the ready event before allowing to press the checkout button.
