### ISSUE TITLE
RecurlyJS is blocked by PrivacyBadger

### ISSUE THREAD

**Issue by iam4x** [recurly/recurly-js#468]
![image](https://user-images.githubusercontent.com/893837/41913600-05f9eff2-7951-11e8-82ce-4baa14ec055d.png)

![image](https://user-images.githubusercontent.com/893837/41913700-4a8fec0c-7951-11e8-82d7-5e4eda32366a.png)

**Comment by chrissrogers** [comment]
Thanks for notifying us! I've submitted a PR to PrivacyBadger to yellowlist our domain.

**Comment by ghostwords** [comment]
Hi @iam4x,

Hello! Could you run the following script in your Badger's background page console and share what it prints out?
```javascript
(function () {
  const STR = "recurly";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
```
To get to the background page console in Chrome, visit `chrome://extensions`, make sure "Developer mode" is checked, click on the "background page" link in Privacy Badger's row, and select the Console tab.

In Firefox, visit `about:debugging`, enable add-on debugging, click Debug next to Privacy Badger, click the OK button on the popup warning about remote debugging, and enter the above script into the console after the >>.

**Comment by chrissrogers** [comment]
Cheers for the debug infrmation @ghostwords

**Comment by iam4x** [comment]
Thank you for the great reactivity, here is the debug output:

![image](https://user-images.githubusercontent.com/893837/41977820-a7cd791e-7a20-11e8-9e26-42e9e24d2bbf.png)

**Comment by ghostwords** [comment]
Yes, as I wrote back in the [Privacy Badger issue](https://github.com/EFForg/privacybadger/pull/2077#issuecomment-400495398), if Recurly doesn't track its users and is able to comply with the [EFF Do Not Track policy](https://www.eff.org/dnt-policy), posting the policy on compliant domains will tell Privacy Badger to always allow those domains to load.

Privacy Badger doesn't know whether the data it sees being passed back and forth is used for tracking or legitimate customer-serving purposes only.

**Comment by chrissrogers** [comment]
recurly.com has been added to the PrivacyBadger yellowlist. Thanks again for reporting this!
