### ISSUE TITLE
Fraud module and card field

### ISSUE THREAD

**Issue by roman-mateush** [recurly/recurly-js#469]
hi all
In our project, we would like to use only one `card` filed instead of `number`, `month`, `year` and `cvv` fields. Also, we use `fraud `module which binds with `number` field. When I try to use only `card` field without number field, I get an error - `There was an error finding a form to inject the data collector fields using selector '[data-recurly=number]`. Does exist any way to use `card` field and `fraud` module together?

**Comment by chrissrogers** [comment]
Hi! I do apologize, but this is a bug. We've begun work on a fix and I will give you updates here as we make progress. Thanks very much for creating an issue.
