### ISSUE TITLE
Problem with Diners club number, the caret wrongly moves inside the string.

### ISSUE THREAD

**Issue by SpataruLoredana** [recurly/recurly-js#476]
Type the following card number 3056 930902 5904 or 3852 000002 3237 (Diners Club card number).
After typing the 11th digit of a Diners club CC number, the caret wrongly moves inside the string.

This problem appears both on individual card fields and the combined card fields.

**Comment by chrissrogers** [comment]
Thanks for reporting this @SpataruLoredana. Our card formatting is currently achieved through the jessepollak/payment library, so the fix will need to be implemented there. I'll open an issue there and take a look at a fix.

**Comment by chrissrogers** [comment]
Closing this for now and moving work over to the payment library
