### ISSUE TITLE
[Hosted pages] Current email address can be changed into an invalid email address with no error generated

### ISSUE THREAD

**Issue by SpataruLoredana** [recurly/recurly-js#481]
This problem appears on Hosted pages. If we try to change a current valid email address into something like "email@domain..com" or "email@-domain.com" the address passes the validation.

**Comment by chrissrogers** [comment]
Hi! would you mind sending this note to support@recurly.com? It will be easier for them to keep in touch with you about an issue related to hosted pages, as issues on this repository are more meant for issues specific to Recurly.js.
