### ISSUE TITLE
Removing an addon from Pricing instance causes "invalid-item" error

### ISSUE THREAD

**Issue by ollipuu** [recurly/recurly-js#486]
It seems there is an issue when removing an addon from a Pricing instance. The addons are stored into the items object under key "addons" in https://github.com/recurly/recurly-js/blob/7204a30ba2e7ee04ea98c1a7432ea41070fa8d78/lib/recurly/pricing/subscription/index.js#L154

However, when removing an addon (setting the quantity as zero), the code is searching for key "addon" (without the "s"), because Pricing.remove is called with parameter { addon: 'addon_code' } in https://github.com/recurly/recurly-js/blob/7204a30ba2e7ee04ea98c1a7432ea41070fa8d78/lib/recurly/pricing/index.js#L112-L114

And therefore an error is returned.

**Comment by chrissrogers** [comment]
Thanks for the report @ollipuu -- I'll have a look at this.

**Comment by chrissrogers** [comment]
Would you mind giving me a specific scenario where this error emits? Are you using the Pricing class directly or attaching it to a form?

**Comment by ollipuu** [comment]
This happens in both scenarios. I have a form where the user can select the product (plan) and add/remove selected addons from the cart. The addon is either selected or not, so the user can not control the number of addons in the cart, unless they purchase multiple products.

So let's assume we have the following items in the form:

Plans: Product 1
Addons: AddonA, AddonB, AddonC

If the user selects for example AddonA and AddonC and chooses to purchase 5 products, the pricing instance is used as follows:

```
pricing
    .plan('product1', { quantity: 5 })
    .addon('addonA', { quantity: 5 })
    .addon('addonB', { quantity: 0 })
    .addon('addonC', { quantity: 5 })
```

In this case the error is emitted with addonB. If the user decides that the Addon C isn't needed after all, the quantity is set to 0 and the error is emitted with B and C.

Am I just using the class incorrectly? I tried to follow the documentation closely, but it could be that I misunderstood something :)

**Comment by chrissrogers** [comment]
Thanks again for the report, and especially the great detail on reproducing the bug. The linked PR addresses the issue and adds some specs. Cheers!

**Comment by ollipuu** [comment]
Awesome, thanks for the quick fix!
