### ISSUE TITLE
Plan-restricted coupon works for another plan too

### ISSUE THREAD

**Issue by ollipuu** [recurly/recurly-js#488]
While building our webshop I stumbled into an issue with coupons. There is a closed issue #175 closely related to this, as the steps to reproduce are exactly the same, although the inverse version I couldn't reproduce.

So we have two plans, planA ($100) and planB ($237) and we have a coupon (20% off) that can be used to planB only. 

```
// RESULT: error: {name: "api-error", code: "not-found", message: "this coupon cannot be redeemed"}
myPricing.plan('planA', { quantity: 1 }).coupon('myCoupon');

// RESULT: price: { now: {subtotal: "189.60", plan: "237.00", addons: "0.00", setup_fee: "0.00", discount: "47.40", total: "189.60"} }
myPricing.plan('planB', { quantity: 1 }).coupon('myCoupon');

// RESULT: price: { now: {subtotal: "80.00", plan: "100.00", addons: "0.00", setup_fee: "0.00", discount: "20.00", total: "80.00"} }
myPricing.plan('planA', { quantity: 1 }).coupon('myCoupon'); 
```

Thanks,
Olli

**Comment by chrissrogers** [comment]
Thanks very much for the report, and sorry to not update you sooner. I was able to verify the issue and have written a fix which should go into the next version. No release date as yet, but I will keep you apprised.

**Comment by ollipuu** [comment]
Great, thanks for the fix!
