### ISSUE TITLE
Object doesn't support property or method 'assign'

### ISSUE THREAD

**Issue by janiscp** [recurly/recurly-js#496]
Experienced this error with v4.94

![image](https://user-images.githubusercontent.com/998632/49494142-93505400-f899-11e8-9e2d-4163d72792ff.png)

You removed it? https://prnt.sc/lqvxb4

**Comment by dotDeeka** [comment]
We also began experiencing this error in IE 11 on our Production site. Does Recurly.js not support IE 11 anymore?

**Comment by janiscp** [comment]
they removed it--- 
![image](https://user-images.githubusercontent.com/998632/49518375-76d40c00-f8d9-11e8-9128-6de1c79a3381.png)


Based from the release notes-- https://github.com/recurly/recurly-js/releases/tag/v4.9.4

**Comment by dotDeeka** [comment]
Yep. If I'm not mistaken, this will break all implementations in IE 11. Now if the intention was to no longer support IE 11 that's fine, but it shouldn't have been released as part of a patch release.

That's the way I look at it anyway.

**Comment by dotDeeka** [comment]
Thank you very much @chrissrogers for the quick fix

**Comment by chrissrogers** [comment]
An update on this: our unit tests specifically test IE11 against bare `Object.assign` calls. We removed the `babel-transform-object-assign` plugin as part of a move to `babel-env` standards, and expect that these transforms would still take place, thus retaining IE11 support. The test environment appears to add an `Object.assign` that was not present in the production version, thus the unit tests did not fail as expected with the missing transforms. I'll update here with further findings.
