### ISSUE TITLE
Fix spacing of expiry and CVV in the Card field

### ISSUE THREAD

**Issue by Stovetopdropp** [recurly/recurly-js#502]
Wanted to follow up with this issue that was logged last spring. 
https://github.com/recurly/recurly-js/issues/438

We're running into the same issue. 

In order to make `inputType: 'text'` to display correctly, we need to set the fontSize to 9px, which is still fairly tight.
Using any font that small would break any sort of UX/ accessibility standards. 

This is what it looks like on smaller screens with size 10px font (using `fontFamily: 'sans-serif'`)

<img width="400" alt="recurly_spacing_issue" src="https://user-images.githubusercontent.com/15370366/50918518-6e0db300-140e-11e9-9240-57d572669f66.png">

**Comment by chrissrogers** [comment]
Hi! Happy to help. Do you have a link to a live demo with your field configuration? A jsfiddle or otherwise would be just fine as well. It always helps to have a concrete example to observe and see how we can improve the spacing.

**Comment by Stovetopdropp** [comment]
This is the configuration we are using

``` javascript
export function configureRecurlyJs(cardNumberPlaceholder, expirationPlaceholder, cvvPlaceholder) {
    // eslint-disable-next-line no-undef
    recurly.configure({
        publicKey: xxxx
        fields: {
            card: {
                displayIcon: true,
                format: true,
                inputType: 'select',
                style: {
                    color: '#4f4f4f',
                    fontFamily: 'sans-serif',
                    fontSize: '14px',
                    placeholder: {
                        color: '#A8A8A8 !important',
                        content: {
                            number: cardNumberPlaceholder,
                            expiry: expirationPlaceholder,
                            cvv: cvvPlaceholder,
                        },
                    },
                    invalid: {
                        fontColor: '#D82E11',
                    },
                },
            },
        },
    });
}
```

**Comment by chrissrogers** [comment]
Brilliant, thanks very much for that. I'll have a look at this to see what can be done.

**Comment by Stovetopdropp** [comment]
Hey @chrissrogers - just checking in to see if any updates have been made on this front.

**Comment by chrissrogers** [comment]
@Stovetopdropp I've allotted some time this week to dedicate to working out some padding adjustments, so unfortunately it's still in progress but I will absolutely update here when progress has been made.

Have you played around with the spacing yourself, in dev tools even, to determine what values work best for your desired layout? I'd be keen to use those as a baseline to determine the best fix here.

**Comment by Stovetopdropp** [comment]
Have you been able to look at this? Don't have specific pixel values, The idea is that this are can be responsive, and look good on a mobile devices.

**Comment by chrissrogers** [comment]
So I think we can take a closer look at the way padding is determined between the expiry and cvv for tighter placements and wider typefaces. The default typeface is pretty thin and should render well on mobile devices, but once wider ones are requested, the two fields can collide some.

If in the course of testing and playing around with layouts for this you find a spacing that is more universally appropriate for your needs, I would be glad to hear it, as that will help us determine which parameters need adjusting.

**Comment by chrissrogers** [comment]
Just wanted to provide a long due update here. We have some changes coming out next week that will adjust the sizing calculations for the expiry and cvv fields. In doing so, we made sure to incorporate this exact case. We are confident that the adjustments will improve the display of the card field for nearly all circumstances.

**Comment by chrissrogers** [comment]
We deployed this layout change yesterday. I'll close this issue for now. Any feedback you have on the layout (or anything, really) is massively appreciated, as we want to do all we can to create an excellent user experience.
