### ISSUE TITLE
Add "adyen-error" to ERRORS

### ISSUE THREAD

**Issue by openinformation** [recurly/recurly-js#506]
Errors returned by the Adyen frame are labeled `adyen-error`, which is not present in the ERROR map. Results in `Uncaught Error: invalid error: adyen-error`

**Comment by chrissrogers** [comment]
@openinformation thanks very much for reporting this! We'll get straight to adding the error in.

**Comment by chrissrogers** [comment]
Hi @openinformation! We have just released [v4.9.5](https://github.com/recurly/recurly-js/releases/tag/v4.9.5) to our CDN, which includes the addition of the `adyen-error` definition. As ever, thanks for the report and do feel free to create any issues for things you'd like to see in RJS.

**Comment by openinformation** [comment]
Thanks!
