### ISSUE TITLE
invalid-public-key "Public key not found" on recurly.token call

### ISSUE THREAD

**Issue by natonnelier** [recurly/recurly-js#512]
Token generation is throwing the following error:
```
code: "invalid-public-key"
message: "Public key not found"
name: "api-error"
```

I'm using v4 of the library `https://js.recurly.com/v4/recurly.js` and set it up according to your docs for [Getting a Token](https://dev.recurly.com/docs/recurly-js-getting-started):

public_key is set here: `recurly.configure('ewr1-my-public-key');`
This seems to be ok since I can see it in the object in console: 
```
recurly.config: {...}
  publicKey: 'ewr1-my-public-key'
```

But the script for token generation triggers the error:
```
$('form').on('submit', function (event) {
    var form = this;
    event.preventDefault();
    recurly.token(form, function (err, token) {
      if (err) {
        console.log(err);
      } else {
        form.submit();
      }
    });
  })
```

**Comment by natonnelier** [comment]
thanks @chrissrogers , your comments helped. I had a second recurly instance running, once I removed it problem was solved.

**Comment by chrissrogers** [comment]
Great! Happy to help any time, so don't hesitate to create an issue with any questions or suggestions of any kind.
