### ISSUE TITLE
Is self-hosting recurly.js a viable option?

### ISSUE THREAD

**Issue by jjt** [recurly/recurly-js#518]
We're beginning to enforce a policy for JS hosted on 3rd party domains have subresource integrity. From #450 it sounds like there's no way to ensure that we pin to a specific version from your CDN, so we'd have to self-host.

Do you adhere to semver? ie. if we're running v4.8.6 self-hosted, would there be any problems now that the current version is v4.9.5?

**Comment by chrissrogers** [comment]
Hi @jjt. We do adhere to semver and will not make breaking changes within major versions (ex: 4.x), so you are safe to upgrade.

**Comment by jjt** [comment]
Thx so much :)

**Comment by chrissrogers** [comment]
I'd encourage taking a look through the [CHANGELOG](https://github.com/recurly/recurly-js/blob/master/CHANGELOG.md) as well just to see what has changed between versions. Cheers!
