### ISSUE TITLE
React Native Library?

### ISSUE THREAD

**Issue by curatehealth** [recurly/recurly-js#521]
What is the best way to integrate Recurly.js into React Native? I am creating a iOS and Android app. @chrissrogers

**Comment by chrissrogers** [comment]
Hi @curatehealth, great question. 

We are working on a React component for Recurly.js right now. However, it will unfortunately not initially be compatible with React Native. We rely on iframes to sandbox customer card data and ensure PCI compliance. The React Native equivalent to this is a `WebView`, which have historically had issues with `postMessage` message propagation, which we rely on to facilitate tokenization and other behaviors.

We continue to monitor [this project in particular](https://github.com/react-native-community/react-native-webview) for potential ways that we can provide a React Native compatible runtime that is compatible with our need to sandbox sensitive customer information.

In the meantime, it _may_ be possible to utilize a WebView in some manner to display a checkout page running Recurly.js itself. We have not tested this ourselves for compatibility, though. **Please do note** that payments initiated through iOS applications for all goods, and digital goods in particular, are subject to Apple's Terms and Conditions, which restrict most payments to being facilitated by Apple itself. The only way around this typically is to host your subscription checkout outside of your App.

Hopefully this reply was helpful in some way. Please feel free to add issues with any other questions or suggestions you have.

**Comment by brajeshsipl** [comment]
@chrissrogers Any updates on a React Native version of Recurly.js as react-native-webview community launched the new version.

**Comment by chrissrogers** [comment]
Hi @brajeshsipl — we don’t have any concrete updates as yet, but thank you for the heads up in the new react-native-webview version. We’ll have a look through and see how that impacts our compatibility prospects. This definitely remains on our radar.

**Comment by Levils114** [comment]
@chrissrogers any update about react native version of Recurly.js?

**Comment by naleon** [comment]
@chrissrogers any update about react native version of Recurly.js?

**Comment by chrissrogers** [comment]
Our CardElement is still limited by communication instability from native webviews to native app context.. so our recommendation for the best customer experience right now is to contain payment flows entirely within webviews. We're keeping an eye on any developments in those APIs, though.
