### ISSUE TITLE
Return an Error when actionTokenID is not provided to ThreeDSecure constructor

### ISSUE THREAD

**Issue by cfortuner** [recurly/recurly-js#536]
Hi! 

Currently, there doesn't seem to be a way to know if the ThreeDSecure Class was initialized correctly with the actionTokenID.

https://github.com/recurly/recurly-js/blob/ee3f1ecb055d06955e53358be7c193f6f8ece74e/lib/recurly/risk/three-d-secure/three-d-secure.js#L46-L65

Can you provide some details about what it means to make the class "act as a null strategy"?

It would be nice if the constructor returned an error when actionTokenID was not provided.

**Comment by chrissrogers** [comment]
Certainly, we can do that.

The comment about acting as a null strategy just means that it's intended to operate in an API-complete way, but not perform any actions. Thus, if a given `actionToken` is malformed or there was a network error, the lack of a strategy won't cause cryptic errors.

I think it's appropriate to add some additional helpful validation errors though, in case the `actionToken` is blank, or malformed in some manner.

**Comment by chrissrogers** [comment]
This was closed since the supporting code change has been merged into master. Once I have a release date designated, I'll let you know here!

Cheers again, and thanks for the report!
