### ISSUE TITLE
Calling Recurly.configure multiple times doesn't re initialize Fraud

### ISSUE THREAD

**Issue by cfortuner** [recurly/recurly-js#539]
I am noticing that when I try to configure recurly multiple times, the Fraud object isn't recreated?

Is this intended? 

I am trying to use the Fraud object to get the fraud_session_id but it only seems to be added when I first configure recurly.

**Comment by chrissrogers** [comment]
Hi @cfortuner -- happy to help here. Would you mind providing a sample of your initial and subsequent configure calls? That will help me determine the runtime ad debug a bit for you.

When you make the subsequent configure call, does `recurly.fraud` become undefined, or is it that the `Fraud` instance's properties are not being updated as expected?

**Comment by cfortuner** [comment]
Hey! 

Both calls use this: 
{
      publicKey: this.props.recurlyPublicKey,
      fraud: {
        kount: { dataCollector: true }
      }
}

The recurly.fraud is still defined but the fraud_session_id is not attached to the form in the subsequent call.

**Comment by chrissrogers** [comment]
Thanks! I'll make a note to look through this as soon as possible and let you know what I find out.

**Comment by cfortuner** [comment]
@chrissrogers 

Discovered that this issue was on my end. Sorry if you already started investigating!

**Comment by chrissrogers** [comment]
Ah! Okay, no, no worries at all. feel free to post any issues or suggestions as you encounter them!
