### ISSUE TITLE
Emit fraud_session_Id instead of exposing it in the HTML

### ISSUE THREAD

**Issue by cfortuner** [recurly/recurly-js#541]
Hey! 

I'm using the Fraud class to generate a Fraud Session Id for use with Kount Data Collection and I was wondering if this is vulnerable to a user spoofing the value?

Once the fraud_session_id input is attached to the form, could the user potentially change the value before we receive that value?

https://github.com/recurly/recurly-js/blob/5038091ec93233f6ff9bd2f842632c76b6f2cfa0/lib/recurly/fraud.js#L101

If so, can we just provide the fraud_session_id in the emitted event?
https://github.com/recurly/recurly-js/blob/5038091ec93233f6ff9bd2f842632c76b6f2cfa0/lib/recurly/fraud.js#L89 

Let me know if this makes sense or if you want me to submit a PR!
Thanks,
Colin

**Comment by chrissrogers** [comment]
Howdy!

It's certainly within the realm of possibility that a user could change the `fraud_session_id` in an intercept manner. However, such an intercept would be possible whether the value is passed into the form and submitted with tokenization (current behavior) or if it is emitted by the fraud module to a handler.

The assurance of lack of manipulation can only come through transaction handling policies with the fraud analysis provider and gateway -- enacting a policy that a transaction must have valid and passing fraud analysis for the transaction to succeed. It would be exceedingly difficult for a user to manipulate the `fraud_session_id` to a passing state that will circumvent fraud analysis given such a policy.

If you would like to read the `fraud_session_id` via a listener, we can certainly consider a feature request for it. The challenge is that, based on the fraud analysis provider, the output from the fraud data collector may differ. But I do think it's a good feature request.

Hopefully that answers some of your concerns -- happy to follow up with any updates for an FR via support as well!

**Comment by cfortuner** [comment]
@chrissrogers Thanks for the great response! I'm curious to know more about how users could intercept the value emitted from the fraud module. Could you point me any docs/info about how a bad actor might do this? 

Since both methods of retrieving the `fraud_session_id` could be intercepted I think its okay to hold off on updating this for now. 

Thanks again for the help!

**Comment by chrissrogers** [comment]
Were we to emit a `recurly.fraud.on('done');` event, a bad actor could, for example, emit the `done` event manually to send a spoofed session id ahead of the real one. The difficulty of course is in creating a valid spoofed value -- a transaction policy that enforces fraud analysis would be very difficult to circumvent.
