### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by wcauchois** [recurly/recurly-js#551]
In this section documenting the pricing API,

https://dev.recurly.com/v2.6/docs/pricing#section-pricing-api

An example is given as follows:

```javascript
var pricing = recurly.Pricing();

pricing
  .plan('basic', { quantity: 1 })
  .currency('USD')
  .addon('addon1', { quantity: 2 })
  .coupon('coop')
	.giftcard('518822D87268C142')
  .address({
    country: 'US',
    postal_code: '90210'
  })
  .tax({
    tax_code: 'digital',
    vat_number: ''
  })
  .catch(function (err) {
    // err.code
  })
  .done(function (price) {
    // price object as emitted by 'change' event
  });
```

In this example `giftcard` is specified as all lowercase, but I believe the method is actually camelcased as `giftCard`.

Minor thing but it cost me a few minutes so I figured I would post here!

**Comment by dbrudner** [comment]
Hi @wcauchois, thanks for taking the time to open this!

If you wouldn't mind, would you also share the code you implemented for your pricing setup?

**Comment by chrissrogers** [comment]
We're in the process of migrating to a new `Pricing` class API that supports multiple subscriptions and adjustments, `recurly.Pricing.Checkout`. This newer API implements `giftCard` (camel-cased), but the current `recurly.Pricing` still implements `giftcard` (no camel-casing). Once we promote `recurly.Pricing.Checkout` as the primary pricing class in a subsequent version, we'll update the documentation to reflect the name-change, and call it out in a migration document.

Thanks for the keen eye on documentation! It's massively appreciated.
