### ISSUE TITLE
Have discreet card fields been deprecated?

### ISSUE THREAD

**Issue by thisleenoble** [recurly/recurly-js#552]
I'm attempting to update a client's registration interface to use v4. Their pre-existing form uses discreet fields (number, month, year, cvv) to capture the card data. Using the test card details with the sandbox I am consistently getting an error from the recurly.token call complaining that the values for these fields are invalid.

I downloaded and installed the Recurly Examples to see what I was missing. The only 3DS example uses the card (div) interface and appears to pass validation at this point using the same card details and sandbox. I then altered the example HTML changing the card div to discreet card fields and the example now reports exactly the same errors as the client's app.

The documentation (https://dev.recurly.com/docs/recurly-js-getting-started) states that either method is valid - discreet fields or card interface, but I'm not finding that. Indeed this previous issue (https://github.com/recurly/recurly-js/issues/473) doesn't contradict that, although provides a better explanation of the changes.

My client is always sensitive to UI changes on their site and it may be that I have to inform them that we'll have to change the interface if we want it to work, however I'd like if possible to know why discreet fields do not appear to work in contradiction to the documentation.

**Comment by chrissrogers** [comment]
Hi @thisleenoble,

We currently support the discreet card fields and have no plans to deprecate or remove them. I'd be happy to help figure out the error you're experiencing though! Are you able to replicate the issue in a jsfiddle or similar environment, or share the JavaScript calls and html you're using to set up the form? If you'd rather not share publicly then we'd be more than happy to assist via support@recurly.com

**Comment by chrissrogers** [comment]
Reading into your question a bit: are you setting up the discreet card fields as `div`s as well? It is necessary to do so as of v4, whether using the [combined](https://dev.recurly.com/docs/recurly-js-getting-started#section-combined-card-field) card field or [individual](https://dev.recurly.com/docs/recurly-js-getting-started#section-individual-card-fields) (discreet) card fields; however, tokenizing card data from `<input>` fields is no longer supported as of v4, as . The issue you linked, #473. and the [upgrading from v3](https://dev.recurly.com/docs/recurly-js-upgrading#section-upgrading-from-v3) section of the docs go into more detail.

**Comment by thisleenoble** [comment]
Ah! Despite staring at the documentation showing card vs discreet fields, I hadn't noticed that the elements had been changed to divs and wrongly assumed that the data-recurly attributes, which are identical to the client's site, were all that was required. Thanks for your help.

**Comment by chrissrogers** [comment]
Of course! Glad to help out.
