### ISSUE TITLE
3ds test iframe not returning three-d-secure-token

### ISSUE THREAD

**Issue by Miqlaj** [recurly/recurly-js#553]
Hello,

I have problem with implementation of 3ds verification for Recurly, i have followed example from https://github.com/recurly/recurly-js-examples/blob/master/public/3d-secure/authenticate.html

My problem is that first iframe is loading correctly, but after clicking "
Succeed Test Authentication" returns nothing to my threeDSecure.on('token' funcition(){}) or threeDSecure.on('error', error); . It jus load iframe with information "To complete your checkout process, please close this browser tab and return to your checkout form." Thanks for any responses.

My view file
https://pastebin.com/irCuGr48
```

    <form id="pm-recurly-form-3ds" method="post" action="<?php echo esc_url( get_permalink( get_queried_object_id() ) ); ?>subscription/pay/">
                <div id="container-3ds-authentication" class="three-d-secure-auth-container col-12 " ></div>
                <div class="three-d-secure-submitting-messagge col-12">
                Authenticating your payment method...
                </div>
                <?php wp_nonce_field( 'pm-register-subscription-nonce' ); ?>
                <input type="hidden" name="pm-form-request" value="register-subscription" />
                <input type="hidden" name="pm-price-plan" value="<?php echo esc_attr( $pm_price_plan ); ?>">
                <input type="hidden" name="three-d-secure-token" id="three-d-secure-token" value="">
                <input type="hidden" name="recurly-token" id="recurly-token" value="">
            </form>
```

My JS file
https://pastebin.com/7zYDAEJs

 ```
   // We expect this page to load with the following parameter pattern
      // `/3d-secure.html#token_id=xxx&action_token_id`
      // This is a simple parser for that pattern. You may use window.URLSearchParams
      // instead if IE11 support is not needed
      var hashParams = location.hash.substr(1).split('&#038;').reduce(function (acc, i) {
        var [k,v] = i.split('=');
        acc[k]=v;
        return acc;
      }, {});
      // Configure Recurly.js
      recurly.configure(recurly_key);
      // In order to remain backend agnostic, this example passes the Recurly.js credit card token
      // to this page via the URL hash. Here we add it to the form so that it will be passed
      // to our backend
      document.querySelector('#recurly-token').setAttribute('value',hashParams.token_id);
     
      // Now we construct the 3-D Secure authentication flow
 
        var risk = recurly.Risk();
        var threeDSecure = risk.ThreeDSecure({ actionTokenId: hashParams.action_token_id });
        var container = document.querySelector('#container-3ds-authentication');
 
 
        // Handle errors that occur during 3-D Secure authentication
        threeDSecure.on('error', error);
        // 'token' is called when your user completes the 3-D Secure authentication flow
        threeDSecure.on('token', function (token) {
            console.log(token);
          // place the result token in your form so that it will be submitted
          // when the customer re-submits
          document.querySelector('#three-d-secure-token').setAttribute('value',token.id);
          // Hide the container once we have a token
          container.style.display = "none";
          // Show the loading message
          document.querySelector('.three-d-secure-submitting-messagge').style.display = "block";
          // submit the form automatically
          recurly_form_verify.submit();
        });
 
        // Attach our 3D Secure session to the container
        threeDSecure.attach(container);
        // Show the container
   
        container.style.display = "block";
      // runs some simple animations for the page
      document.querySelector('body').classList.add( 'show' );
```

First iframe
![Zrzut ekranu 2019-09-14 o 12 57 21](https://user-images.githubusercontent.com/17083653/64908598-adf60a00-d702-11e9-8ea0-b5711eb55d72.png)

Second iframe
![Zrzut ekranu 2019-09-14 o 12 58 33](https://user-images.githubusercontent.com/17083653/64908603-b77f7200-d702-11e9-891d-578042dcece0.png)

**Comment by Miqlaj** [comment]
Sorry, wrong repo. I moved the issue to [https://github.com/recurly/recurly-js-examples/issues/48](url)

**Comment by chrissrogers** [comment]
Hi @Miqlaj -- happy to help. Do you notice any errors in the browser console?

Also in the browser console, would you mind setting `localStorage.debug = 'recurly:*'`? This will enable verbose debugging, and help us understand what may be happening. A screenshot of the debug messages that appear immediately after clicking "Succeed Test Authentication" would be most helpful.

**Comment by Miqlaj** [comment]
Thank you for quick response @chrissrogers ! Sure its look like that - let me know what else do you need.
![image](https://user-images.githubusercontent.com/17083653/64912289-57ea8c00-d72d-11e9-9729-3d5fb26a8b57.png)

**Comment by chrissrogers** [comment]
the message stating `destroying bus` is typically encountered when `recurly.configure` is called. It appears that the message bus that will relay the success message from the iframe to your listener is being discarded due to a call to `recurly.configure`. Is there a chance this is happening?

Using the authentication example as a base, which it seems like you have done as well, the following debug logging is typical:

![](https://cldup.com/7Yh2mrYO31-3000x3000.png)

**Comment by Miqlaj** [comment]
Thank you very much @chrissrogers! I got this project as legacy after someone else. It turned out that in a completely different file there were additional recurly.confiugre used for styling.

`
 setTimeout(() => {
    if(window.recurly) {
      window.recurly.configure({
        fields: {
          all: {
            style: {
              fontFamily: 'Lato',
              fontSize: '14px'
            }
          }
        }
      })
    }
  }, 1000)
`
Again thank you, I wouldn't have found it without you.

**Comment by chrissrogers** [comment]
Very glad to hear that! And more than happy to help.
