### ISSUE TITLE
Is threeDSecure.remove() officially supported?

### ISSUE THREAD

**Issue by thbar** [recurly/recurly-js#559]
I use a single page sign-up form which includes non Recurly information, the billing information & also does the 3DS challenge (by temporarily hiding the form while this is done).

For some reason, if I simulate a 3DS failure, followed by a new POST then a 3DS challenge again, the challenge HTML content is displayed much lower in the page (I presume the previous one is "blank but still taking space").

If I call `threeDSecure.remove()` (which I saw in the code) first thing when receiving the `error` or `token` events, things go perfectly fine instead:

```coffeescript
risk = recurly.Risk()
threeDSecure = risk.ThreeDSecure({ actionTokenId: jsonResponse.three_d_secure_action_token_id })

threeDSecure.on 'error', (err) => 
  threeDSecure.remove()
  options['on_three_d_error'](err)

threeDSecure.on 'token', (token) =>
  threeDSecure.remove()
  options['on_three_d_token'](token)

threeDSecure.attach(document.querySelector('#three-d-secure-auth-container'))
```

I can't see `remove()` in the official documentation.

Can I consider it supported?

Many thanks

**Comment by chrissrogers** [comment]
Hi @thbar -- Yes! `remove` is officially supported. I have updated our documentation accordingly: https://dev.recurly.com/docs/recurly-js-3d-secure

Thanks for the question and awesome description of your use-case.
