### ISSUE TITLE
Not possible to style padding on hosted field

### ISSUE THREAD

**Issue by kovcic** [recurly/recurly-js#563]
Hello,

I see that hosted field js is removing padding property from styling config.
That makes issue on Safari (iOS) having default useragent (padding) styles applied:

<img width="476" alt="Screen Shot 2019-11-06 at 9 22 18 AM" src="https://user-images.githubusercontent.com/23143/68281255-8c1c6200-0077-11ea-9a50-5ef23f820949.png">

You can see applied padding values here:

<img width="506" alt="Screen Shot 2019-11-06 at 9 22 30 AM" src="https://user-images.githubusercontent.com/23143/68281287-a22a2280-0077-11ea-954a-6032cb6b1379.png">

is there a way to reset paddings to 0 so I can get something as:

<img width="479" alt="Screen Shot 2019-11-06 at 9 24 00 AM" src="https://user-images.githubusercontent.com/23143/68281372-cf76d080-0077-11ea-98ea-6cde3e456b4f.png">

Thx

**Comment by dbrudner** [comment]
Hey @kovcic! Thanks for taking the time to open this issue, the pictures are super helpful for describing the issue you're experiencing.

If you wouldn't mind, would you pass along the recurly config you're using so we can most accurately reproduce the issue on our end? Thanks again for reporting this!

**Comment by kovcic** [comment]
Hi,

here's the excerpt from my component calling configure:

```
  componentDidMount() {
    const { publicKey, theme } = this.props;
    const { recurly } = window;

    recurly.configure({
      publicKey,
      fields: {
        all: {
          style: {
            fontFamily: theme.typography.fontFamily,
            fontSize: '16px',
            color: theme.palette.text.primary,
          },
        },
        card: {
          displayIcon: false,
          style: {
            placeholder: {
              content: {
                number: translate('item.cc_number.label'),
                expiry: translate('item.cc_expiry.label'),
                cvv: translate('item.cc_cvv.label'),
              },
            },
            invalid: {
              fontColor: theme.palette.text.primary,
            },
          },
        },
      },
    });

    // recurly listeners
    recurly.on('field:submit', this.handleFieldSubmit);
    recurly.on('change', this.handleFieldChange);

    this.setupPricing();
  }
```

I tried to pass `padding` inside `fields -> all -> style` but has no change.
Then I inspected iframe running hosted field (the js code there) and noticed that padding is deleted:

<img width="472" alt="Screen Shot 2019-11-06 at 6 01 34 PM" src="https://user-images.githubusercontent.com/23143/68320012-864a6f00-00bf-11ea-8fe2-95f747d1f77a.png">

That would explain why padding styling via config didn't have any effect.

**Comment by dbrudner** [comment]
Hey @kovcic, to follow up on this, `style.padding` is only valid on individual card fields, not the combined card field you're using. Our recommended way of adding padding to a hosted field is to apply it to the hosted field's parent class (in this case,  `.recurly-hosted-field-card`). From there, you can use media queries or any other solution you'd like to correctly apply style/padding to the field in a mobile environment. For more info, feel free to check out https://developers.recurly.com/pages/recurly-js.html#styling-card-fields.

**Comment by kovcic** [comment]
Alright, I was expecting such answer.

I just wanted to point out that Safari/Chrome on iOS have different padding applied. You can see it here why:

<img width="524" alt="Screen Shot 2019-11-07 at 9 16 40 AM" src="https://user-images.githubusercontent.com/23143/68371706-943fd480-013f-11ea-9355-f5b7dac0e050.png">

I'm not sure why such value (padding: 0.2em 0.5em 0.3em) but I think it would be helpful to have option to reset it so I don't have to handle platform specific css. If you have it enabled for individual card fields, why not also for combined?

Thx

**Comment by dbrudner** [comment]
I hear your concern, though unfortunately, this is unlikely to change in the near future. Thanks again for bringing the issue forward! I hope you’re able to find a satisfactory display option for your card field. If you have any other questions or concerns, feel free to ask away.

**Comment by pjg** [comment]
Here's how my combined CC input looks on iOS :/

![image](https://user-images.githubusercontent.com/10712/69427017-de73a900-0d2e-11ea-9d02-b4dcf2860a21.png)

**Comment by chrissrogers** [comment]
@pjg I'd love to take a look at your display issue more closely. Do you have a URL I can access, and a specific version of iOS/browser ?

**Comment by pjg** [comment]
@chrissrogers here's the URL that you can see this problem in action: http://goscicki.pl/recurly.html

![image](https://user-images.githubusercontent.com/10712/69982861-b9084b80-1535-11ea-9454-240f71cf29c6.png)

Nothing fancy in the config. Also, you need either a real iOS device (verified on iPhone X and 11 Pro) or a MacOS Simluator app from XCode.

**Comment by dbrudner** [comment]
@pjg We took a look and verified, it looks like you're spot on. We'll take a closer look at examining solutions and hope to include a fix in the next release. Thanks for reporting, the images and link are super helpful! If you have any further questions or comments, feel free to add them below.
