### ISSUE TITLE
Applying multiple coupons to a Pricing object

### ISSUE THREAD

**Issue by wcauchois** [recurly/recurly-js#565]
When creating a purchase using the Recurly API, you can provide multiple coupon codes. However, it seems that with the JavaScript Pricing API you can only apply one coupon at a time to a pricing object. First of all, am I correct in that understanding? And secondly, if that's the case would it be possible to update it to be able to handle multiple coupons?

**Comment by chrissrogers** [comment]
Hi @wcauchois yep, you are correct that Pricing in Recurly.js is constrained to a single coupon. I'd be happy to add a feature request for multiple coupon support as well, as it seems like a good use case. If you have any specific things you'd like to accomplish with it, I'd be glad to add those as well. Cheers!

**Comment by chrissrogers** [comment]
Closing this -- we'll be tracking this as a feature request.
