### ISSUE TITLE
Wrong discount and subtotal next values

### ISSUE THREAD

**Issue by GabrielHaba95** [recurly/recurly-js#572]
### Description
When applying single-use coupon (either with amount or rate) on a subscription (either monthly or yearly) which starts first with 7-days free trial, the discount next is always 0$ and subtotal next is always unchanged(=plan unit value)
This problem is only present on single-use coupon, other ones such as forever and temporal coupons work prefectly : all values are correct.

### Example
When creating this new subscription:
Subscription: 199$/month
Free trial 7 days
Coupon:
```
{
  "code": "couponcode",
  "name": "couponname",
  "discount": {
    "type": "dollars",
    "amount": {
      "EUR": 15.0
    }
  },
  "single_use": true,
  "applies_for_months": null,
  "duration": "single_use",
  "temporal_unit": null,
  "temporal_amount": null,
  "plans": [],
  "applies_to_non_plan_charges": false,
  "applies_to_plans": true,
  "applies_to_all_plans": true,
  "redemption_resource": "account"
}
```
—————
Subtotal now: 0$ (normal because of the 7 days free trial)
Subtotal next: 299$ (expected to be 284$)
Discount next: 0$ (expected to be 15$)
Discount now: 0$ (normal because coupon shouldn’t be applied now but after free trial, on next month)

### How we apply coupon and retrieve/display those values
In Haml :
```
= simple_form_for(@subscription, url: subscriptions_path, :html => { id: "recurly-payment-form" }, :defaults => {:required => false}) do |f|
    ...
    7-day free trial, then
    %span{"data-recurly" => "currency_symbol"}
    %span{"data-recurly" => subtotal_next}
    ...
    #discount.mt10{style: 'display: none;'}
         Discount: 
         %span{"data-recurly" => "currency_symbol"}
         %span{"data-recurly" => discount_next}
    ...
    #coupon_container.hidden.mt5
        .controls
           .input-group
              %input.form-control{"data-recurly" => "coupon", :type => "text", :id => 'coupon', :placeholder => 'Coupon code'}
              %input{:type => "hidden", :name => 'coupon'}
              .input-group-addon{onclick: "return false;"} Apply
```
In Coffeescript:
```
el: "form#recurly-payment-form"
...
@pricing = recurly.Pricing()
@pricing.attach(@$el)
... 
```

### Remarks
I check the @pricing object inside the on 'set.coupon' event listener and we can see discount next in at this moment is also equals to $0 + subtotal which is still equal to plan unit value $299
```
price: {
   ...
   next: {
        addons: "0.00"
        discount: "0.00"
        plan: "299.00"
        setup_fee: "0.00"
        subtotal: "299.00"
        tax: "0.00"
        total: "299.00"
    }
    now: {
        addons: "0.00"
        discount: "0.00"
        plan: "0.00"
        setup_fee: "0.00"
        subtotal: "0.00"
        tax: "0.00"
        total: "0.00"
    }
    ...
```

### Environment
Recurly JS 4.10.3
CoffeeScript 2.4.1

**Comment by dbrudner** [comment]
Appears to be a bug at a quick glance. Thanks for the detailed issue description, we'll look into this.

**Comment by GabrielHaba95** [comment]
> Appears to be a bug at a quick glance. Thanks for the detailed issue description, we'll look into this.

Great Thank you :)

**Comment by GabrielHaba95** [comment]
Do you have any news about it @dbrudner ?

**Comment by dbrudner** [comment]
@GabrielHaba95 I received an e-mailed notification that you commented in this issue yesterday, but I'm not seeing it. 

To give a quick updated, we haven't had time to explore this issue yet, but will do so soon. I'll make sure to keep you in the loop on our progress and findings. Thank you for your continued patience.

**Comment by GabrielHaba95** [comment]
Hi, @dbrudner 

it seems that the fix you put in place does not resolve the issue from our side, `discount_next` and `subtotal_next` values in case of single use coupon
We still receive 0$ and 299$ (considering given example in the description).

Currently if we want to display the real price the user will pay after the free trial, we have
to perform manually such operation : `price.base.plan.unit - coupon.discount.amount` (expected subtotal next value)

We use currently Recurly JS 4.11.0.

Do you hav an idea about that ?

Thank you

**Comment by chrissrogers** [comment]
Hi @GabrielHaba95, just a note that this issue closed when the resulting fix was merged to master, but the fix has not yet been incorporated into a new version. Apologies for the confusion!

You can see the changes that have occurred since v4.11.0 here: https://github.com/recurly/recurly-js/compare/v4.11.0...master

I don't have an exact timeline for the next deploy, but will update you here as soon as we have one established. Once we create the new version, it will be visible [here](https://github.com/recurly/recurly-js/releases) as a `pre-release`. Once we deploy that version to our CDN, the release there will be marked as `Latest release` and the fix will be live!

Thanks again for your detailed report, and I'll keep you informed on our release scheduling as it becomes available.

**Comment by GabrielHaba95** [comment]
> Hi @GabrielHaba95, just a note that this issue closed when the resulting fix was merged to master, but the fix has not yet been incorporated into a new version. Apologies for the confusion!
> 
> You can see the changes that have occurred since v4.11.0 here: [v4.11.0...master](https://github.com/recurly/recurly-js/compare/v4.11.0...master)
> 
> I don't have an exact timeline for the next deploy, but will update you here as soon as we have one established. Once we create the new version, it will be visible [here](https://github.com/recurly/recurly-js/releases) as a `pre-release`. Once we deploy that version to our CDN, the release there will be marked as `Latest release` and the fix will be live!
> 
> Thanks again for your detailed report, and I'll keep you informed on our release scheduling as it becomes available.

Great, no problem
Thank you for your response :)

**Comment by chrissrogers** [comment]
To follow up, this change has been deployed today.
