### ISSUE TITLE
Missing Fields in Internet Explorer 10

### ISSUE THREAD

**Issue by rsalbarico** [recurly/recurly-js#578]
Hi, does Recurly has compatibility issue on Internet Explorer 10? I've tested this using Windows 7 and Internet Explorer 10 using lambdatest. I've attached this screenshot for reference. [https://prnt.sc/qutruz](url)

**Comment by chrissrogers** [comment]
Hi! We don’t officially support Internet Explorer 10. At this time we support IE 11 and up. You can review our complete browser support list I’m the developer documentation here: https://developers.recurly.com/reference/recurly-js/#support

**Comment by rsalbarico** [comment]
Hi Chris, what was the last version released that supports IE10?

**Comment by chrissrogers** [comment]
We don't recommend using previous versions of this library for security and stability reasons; only to use the latest version distributed over our CDN. Packaging a previous version of this library and distributing it from your own servers may bring about more stringent PCI auditing requirements.

[This commit](https://github.com/recurly/recurly-js/commit/665a91617a8aad568cc16f39d9b851b0c9a1248f#diff-354f30a63fb0907d4ad57269548329e3) from November 2017 removed test cases for IE 10. Microsoft themselves [have ended support for IE 10 as of the 14th of this month](https://support.microsoft.com/en-us/help/4488955/support-ending-for-internet-explorer-10) -- thus I can't recommend extending any support for it beyond that date.
