### ISSUE TITLE
Question on Braintree device data collector

### ISSUE THREAD

**Issue by geoffdutton** [recurly/recurly-js#605]
We're using the advanced fraud management tools as [documented here](https://developers.recurly.com/reference/recurly-js/#braintree-gateway-fraud-integration).

I'm curious if the Recurly api is expecting `deviceData` to be an object or a stringified object?

When you look at the `dataCollectorInstance` object, it looks like this:
```
{
  deviceData: "{"device_session_id":"fe0e0f2291eefe148c073c2d4a8dccf8","fraud_merchant_id":"600000","correlation_id":"60ce7cffa87ca645b338a2039644504b"}",
  rawDeviceData: {
    correlation_id: "60ce7cffa87ca645b338a2039644504b"
    device_session_id: "fe0e0f2291eefe148c073c2d4a8dccf8"
    fraud_merchant_id: "600000"
  }
}
```

Should the configure function receive:
```
recurly.configure({
  // ...
  fraud: {
    braintree: { deviceData: dataCollectorInstance.rawDeviceData }
  }
  // ..
});
```
Or the stringified version?
```
recurly.configure({
  // ...
  fraud: {
    braintree: { deviceData: dataCollectorInstance.deviceData }
  }
  // ..
});
```

Thanks!

**Comment by chrissrogers** [comment]
Great question! It's not super clear in documentation is it. We're expecting the stringified `dataCollectorInstance.deviceData` here.
