### ISSUE TITLE
Add support for SEPA billing info

### ISSUE THREAD

**Issue by thgreasi** [recurly/recurly-js#606]
We are interested at offering the respective billing info form for SEPA payments.
Atm, according to the GoCardless docs, it seems that it's only possible to do that from the self hosted pages.
https://docs.recurly.com/docs/gocardless

**Comment by thgreasi** [comment]
Oh I just now saw https://github.com/recurly/recurly-js/pull/579 so it might be already there I guess and it was just the docs that were missing the iban field and me not finding "SEPA" in the repo while searching.

**Comment by dbrudner** [comment]
Thanks for opening this issue! We fixed our documentation to note that `Recurly.js supports sending tokenized bank account (both SEPA and ACH) information to Recurly.`

If you see any other issues in our docs, feel free to open another issue. Thanks for reporting and it's great you were able to solve on your own!
