### ISSUE TITLE
Not able to add new attribute maxlenth to element card element

### ISSUE THREAD

**Issue by AnilkumarBorra** [recurly/recurly-js#639]
fields :{
    number: {
      length: 16,
    },
    month: {
      length: 2,
    },
    year: {
      length: 4,
    },
    cvv: {
      length: 4,
    }
  }

**Comment by dbrudner** [comment]
Hey @AnilkumarBorra , thanks for opening an issue. Can you explain your use case is a bit more and what you're trying to do?
