### ISSUE TITLE
Incomplete typings

### ISSUE THREAD

**Issue by gertsonderby** [recurly/recurly-js#646]
The TS typings found in `/types` are incomplete, causing problems for users.

Example:
Compare configuration typing:
https://github.com/recurly/recurly-js/blob/e03569c39dba8df4b91dc16ab811b024c7fb272c/types/lib/configure.d.ts#L1-L18

With the default configuration 
https://github.com/recurly/recurly-js/blob/e03569c39dba8df4b91dc16ab811b024c7fb272c/lib/recurly.js#L51-L89)

The entire `fields` config section is missing here, making it difficult to style elements properly when using TypeScript.

**Comment by gertsonderby** [comment]
Another example:
https://github.com/recurly/recurly-js/blob/e03569c39dba8df4b91dc16ab811b024c7fb272c/lib/recurly/paypal/index.js#L18-L23
https://github.com/recurly/recurly-js/blob/e03569c39dba8df4b91dc16ab811b024c7fb272c/lib/recurly/paypal/index.js#L83-L85
Versus
https://github.com/recurly/recurly-js/blob/e03569c39dba8df4b91dc16ab811b024c7fb272c/types/lib/paypal.d.ts#L17

**Comment by dbrudner** [comment]
Thanks for letting us know! We'll work on updating our types for this. If you find anything else, feel free to share in this issue as well.

**Comment by dbrudner** [comment]
Thanks again for opening the issue @gertsonderby! We updated the types and released them on DefinitelyTyped https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48625.

If you find anything else, please feel free to open another issue.
