### ISSUE TITLE
Can not use recurly from 18 Dec, 2020 to now

### ISSUE THREAD

**Issue by tringo8311** [recurly/recurly-js#662]
I got error

Uncaught TypeError: Cannot read property 'crypto' of undefined

from script https://js.recurly.com/v4/recurly.js

`function(e, t) {
    var n = self.crypto || self.msCrypto;
    e.exports = function(e) {
        return n.getRandomValues(new Uint8Array(e))
    }
}`

self is undefined

**Comment by chrissrogers** [comment]
Hi @tringo8311 thanks for the report, happy to help here. Do you have any steps to reproduce the error? In which browser are you seeing this error?
