### ISSUE TITLE
Better validation on fly ?

### ISSUE THREAD

**Issue by aldarund** [recurly/recurly-js#679]
Why recurly dont validate and even restrict cvc to 3 or 4 digits based on card number on fly? Its not good UX for user. 
Why recurly dont validate whether this is 15 or 16 or 19 digits cared based on card number on fly? Its again not good UX.
For example in stripe
https://stripe.com/docs/payments/accept-a-payment?platform=web&ui=elements
I can enter non stop just by typing 4242 4242 4242 4242 11/22 123 and get valid form
Same thing in recurly will produce 4242 4242 4242 4242 112 as a card number and no automatic go to next field. Thats so much worse ui so i wonder why its not implemented to detect and handle such things on fly like in stripe?

**Comment by chrissrogers** [comment]
This is a good feature request. We support PANs up to 19 digits, but not all networks do. Thank you!
