### ISSUE TITLE
Multilingual support for Recurly.js

### ISSUE THREAD

**Issue by xpert6** [recurly/recurly-js#681]
Is there any support in Recurly.js for multiple languages?

**Comment by chrissrogers** [comment]
Hi @xpert6, thanks for the question! We support i18n capabilities, but don't provide any language-specific defaults or built-in localization.

That is to say, you can achieve internationalization and localization in recurly.js Elements (by [setting placeholder content](https://developers.recurly.com/reference/recurly-js/index.html#styling-the-card-element)) and in error messages by using [the error code](https://developers.recurly.com/reference/recurly-js/index.html#errors) to inform your internationalization tables and choosing a message you'd like to present to customers.

Hope this helps!
