### ISSUE TITLE
Add a line item for trial in apple pay payment sheet 

### ISSUE THREAD

**Issue by arsendovlatyan** [recurly/recurly-js#686]
When you are integrating Apple Pay via RecurlyJS you don't have much control over payment sheet line items, you cannot add custom items which make sense to me, however our subscriptions are starting with a free trial and there is no way to introduce that in payment sheet. According to this documentation https://developers.recurly.com/reference/recurly-js/index.html#apple-pay you can pass `country`,  `currency`, `label` and `total` or just `recurly.Pricing.Checkout`, it will be nice if we can pass `trial` (maybe just a string) or which is even better if trial will be displayed when `recurly.Pricing.Checkout` is passed.

In result I expect to see first line something like this "30 Day Free Trial     $0.00" as it's recommended here https://developer.apple.com/design/human-interface-guidelines/apple-pay/overview/subscriptions-and-donations/ 

![image](https://user-images.githubusercontent.com/1083615/126327415-6595871b-a1b5-4fb0-8cda-091d9065238a.png)

**Comment by rer7891** [comment]
@arsendovlatyan Thank you for your request. We have made an official feature request to our product team to assess the impact and feasibility of implementing this additional field.
