### ISSUE TITLE
Apple Pay via Braintree causes CSP violation

### ISSUE THREAD

**Issue by chris-hanson** [recurly/recurly-js#767]
Hello. We're looking to implement Apple Pay using Braintree as a our payment gateway. When the Braintree config is set, we're running into a CSP violation:

```
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script
```

We've identified the issue as coming from the use of `Promise.denodeify` which uses the [Function constructor to evaluate code from strings.](https://github.com/then/promise/blob/8.1.0/src/node-extensions.js#L33) This function is used in [apple-pay.braintree.js](https://github.com/recurly/recurly-js/blob/master/lib/recurly/apple-pay/apple-pay.braintree.js#L7) to load the braintree scripts and return a promise.

We would not be so keen to add `unsafe-eval` to our CSP and was hoping you might be able to refactor out the `denodeify` usage. For example something like this could achieve similar `promisifying` without the violation:

```
const promisifyLoadScript = (src) => {
  return new Promise((resolve, reject) => {
    loadScript(src, (err, script) => {
      if (err) reject(err);
      else resolve(script);
    });
  });
};
```

Anyway, hoping we can start a discussion and look at alternatives to modifying our CSP.

Cheers.

**Comment by pollyoaks** [comment]
Related fix for this here: https://github.com/recurly/recurly-js/pull/772

**Comment by chris-hanson** [comment]
Confirmed this issue is fixed for us 👍 Thanks for the quick fix
