### ISSUE TITLE
Cannot read properties of undefined (reading 'api')

### ISSUE THREAD

**Issue by joshunger** [recurly/recurly-js#836]
We're seeing a large increase of errors reported to Bugsnag with the following exception -

```
Cannot read properties of undefined (reading 'api')
```

![image](https://github.com/recurly/recurly-js/assets/2301847/f66ed9bf-8603-4991-9c10-af8902073c39)

Is 4.25.2 being tested on customers that has @cbarton changes https://github.com/recurly/recurly-js/commit/142d5df22c51936a0cec5932c021237c42f09729 ?

I wonder if `payments` still needs optional chaining? I don't have exact repro steps.

Thanks for the help!

**Comment by cbarton** [comment]
Yes, we will have a fix up later today. We were having reports of this and had a tough time tracking it down since our test environments do not have `google` already in the window. Thank you for the report!

**Comment by joshunger** [comment]
@cbarton thank you! Yeah, Google One Tap / Sign In With Google is at `google.accounts` https://developers.google.com/identity/gsi/web/reference/js-reference

**Comment by douglasmiller** [comment]
@joshunger, the fix for this issue has been merged and deployed. Thanks again for the report!
