### ISSUE TITLE
Formatting on DefinitelyTyped update

### ISSUE THREAD

**Issue by MysteryBlokHed** [recurly/recurly-js#856]
It looks like the newest PR to update the types on DefinitelyTyped (DefinitelyTyped/DefinitelyTyped#66861) also reformatted a lot of the code, presumably because this repository's code formatting settings aren't the same as over there.

It might be worth changing the formatting settings to not affect the `types/` directory, although this could also just be considered a non-issue since it doesn't make DefinitelyTyped CI fail and the types are only modified from here. Just figured I'd mention it 🤷🏻‍♂️

**Comment by douglasmiller** [comment]
Thank you for sharing, @MysteryBlokHed. 

There's not much that can be done here since our linting standards differ from those of the DefinitelyTyped repository.
