### ISSUE TITLE
Recurly (3DS) in Test Mode with `<dialog />` elements

### ISSUE THREAD

**Issue by simeydotme** [recurly/recurly-js#876]
Hi,

I'm trying to build out the 3DSecure flow with Recurly, using the test environment.
I have the checkout flow open in a side-panel utilising `<dialog />` and the HTML Api for `TopLayer`.

When the challenge test screen appears (`<iframe name="__privateStripeFrame****">` inside of a `<div>`), it is BEHIND the `TopLayer` and attached to the very beginning of the `<body>`. I have tried two things;

1) set the `attach()` to my `<dialog />`
  ```
  const topModal = document.querySelector('dialog[data-is-top=true]');
  const attachTo = topModal || document.body;
  threeDSecure.attach(attachTo);
```

  - this has no effect (at least for test flow)
2) move the `<iframe />` after it's attached
  - this causes the second (inner) `<iframe name="stripe-challenge-frame" />` to disappear completely (`.ThreeDS2-container` is empty)
  
---

In the screenshot (with some redaction) you can see the Visa Test Card Modal is stuck behind my `<dialog />`'s `::backdrop` . The reason is because the `<dialog />` API promotes it to the `::TopLayer` which cannot be overwritten with a non-top-layer element.

<img width="1142" alt="Screenshot 2024-03-15 at 15 28 31" src="https://github.com/recurly/recurly-js/assets/2817396/8bddc09e-c7ea-4005-8d2c-1595b33c37ac">

---

So the questions are; 
- is this an error only for the test modal?
- is `.attach()` broken?
- what can I do about this?

**Comment by chrissrogers** [comment]
For Stripe's 3-D Secure implementation, we're somewhat limited in our attachment controls. [See code](https://github.com/recurly/recurly-js/blob/master/lib/recurly/risk/three-d-secure/strategy/stripe.js#L43). From that call, they are making some assumptions about modal placement, and aren't going to make use of the DOM attachment point passed to `attach`.

Moving an `<iframe>` would cause it to re-render, and likely to break the communication between the controlling entity on the parent (Stripe.js) and the application inside of the iframe.. that's likely the cause of the disappearance you're seeing.

I'll admit my familiarity with the dialog element and the `TopLayer` are limited, so I'm not sure I can provide any direct help with those.. but if there is no way to lift the Stripe modal element into the `TopLayer`, then it may be best to go the classic modal render route, unfortunately.

**Comment by simeydotme** [comment]
Thanks for the response @chrissrogers  :)
Sadly, our entire frontend design system was recently moved over to `<dialog />` 

But for now, I'm closing the side-panel drawer upon triggering the 3DS flow. And re-opening upon an error or failed challenge.
It's not ideal, as it can wipe out the creditcard fields, but it's the only thing I could come up with.

don't hesitate to @ me if anything changes with the way modals/iframes are rendered 👍

**Comment by simeydotme** [comment]
https://stackoverflow.com/a/75947179/1121532

According to this, it may only be a test-env issue, so I will monitor how it works with a real card payment in prod, and if there's no issue I'll put a flag in to close only in staging/dev.
